insert into mascotas (id, tipo, nombre, edad) values (1, 'ave', 'Tamandua, southern', 96);
insert into mascotas (id, tipo, nombre, edad) values (2, 'ave', 'Coatimundi, ring-tailed', 20);
insert into mascotas (id, tipo, nombre, edad) values (3, 'mamifero', 'Lorikeet, scaly-breasted', 28);
insert into mascotas (id, tipo, nombre, edad) values (4, 'ave', 'Steenbok', 25);
insert into mascotas (id, tipo, nombre, edad) values (5, 'mamifero', 'Kiskadee, great', 95);
insert into mascotas (id, tipo, nombre, edad) values (6, 'ave', 'Common long-nosed armadillo', 40);
insert into mascotas (id, tipo, nombre, edad) values (7, 'mamifero', 'Vine snake (unidentified)', 19);
insert into mascotas (id, tipo, nombre, edad) values (8, 'mamifero', 'Wallaby, dama', 102);
insert into mascotas (id, tipo, nombre, edad) values (9, 'ave', 'Pied kingfisher', 83);
insert into mascotas (id, tipo, nombre, edad) values (10, 'ave', 'Heron, yellow-crowned night', 30);
insert into mascotas (id, tipo, nombre, edad) values (11, 'pez', 'Cockatoo, sulfur-crested', 64);
insert into mascotas (id, tipo, nombre, edad) values (12, 'ave', 'Finch, common melba', 69);
insert into mascotas (id, tipo, nombre, edad) values (13, 'mamifero', 'Fox, bat-eared', 17);
insert into mascotas (id, tipo, nombre, edad) values (14, 'mamifero', 'Hen, sage', 19);
insert into mascotas (id, tipo, nombre, edad) values (15, 'mamifero', 'Magellanic penguin', 40);
insert into mascotas (id, tipo, nombre, edad) values (16, 'mamifero', 'Yellow baboon', 67);
insert into mascotas (id, tipo, nombre, edad) values (17, 'ave', 'Tortoise, asian foreset', 59);
insert into mascotas (id, tipo, nombre, edad) values (18, 'pez', 'Crested bunting', 108);
insert into mascotas (id, tipo, nombre, edad) values (19, 'ave', 'Grouse, greater sage', 44);
insert into mascotas (id, tipo, nombre, edad) values (20, 'ave', 'Blue-footed booby', 24);
insert into mascotas (id, tipo, nombre, edad) values (21, 'ave', 'Caracara, yellow-headed', 20);
insert into mascotas (id, tipo, nombre, edad) values (22, 'ave', 'Ibex', 54);
insert into mascotas (id, tipo, nombre, edad) values (23, 'mamifero', 'Lechwe, kafue flats', 94);
insert into mascotas (id, tipo, nombre, edad) values (24, 'mamifero', 'Southern screamer', 34);
insert into mascotas (id, tipo, nombre, edad) values (25, 'mamifero', 'Wallaby, dama', 108);
insert into mascotas (id, tipo, nombre, edad) values (26, 'mamifero', 'Greater flamingo', 29);
insert into mascotas (id, tipo, nombre, edad) values (27, 'mamifero', 'Ibis, sacred', 62);
insert into mascotas (id, tipo, nombre, edad) values (28, 'ave', 'Tsessebe', 79);
insert into mascotas (id, tipo, nombre, edad) values (29, 'ave', 'Monitor, two-banded', 70);
insert into mascotas (id, tipo, nombre, edad) values (30, 'mamifero', 'Vulture, black', 61);
insert into mascotas (id, tipo, nombre, edad) values (31, 'ave', 'Trumpeter swan', 88);
insert into mascotas (id, tipo, nombre, edad) values (32, 'mamifero', 'Lizard, frilled', 37);
insert into mascotas (id, tipo, nombre, edad) values (33, 'ave', 'Robin, white-throated', 24);
insert into mascotas (id, tipo, nombre, edad) values (34, 'pez', 'Lion, steller''s sea', 78);
insert into mascotas (id, tipo, nombre, edad) values (35, 'ave', 'Brown pelican', 19);
insert into mascotas (id, tipo, nombre, edad) values (36, 'mamifero', 'African polecat', 67);
insert into mascotas (id, tipo, nombre, edad) values (37, 'ave', 'Eagle, bald', 100);
insert into mascotas (id, tipo, nombre, edad) values (38, 'ave', 'Prehensile-tailed porcupine', 108);
insert into mascotas (id, tipo, nombre, edad) values (39, 'ave', 'Red-knobbed coot', 98);
insert into mascotas (id, tipo, nombre, edad) values (40, 'mamifero', 'Vine snake (unidentified)', 36);
insert into mascotas (id, tipo, nombre, edad) values (41, 'mamifero', 'Helmeted guinea fowl', 65);
insert into mascotas (id, tipo, nombre, edad) values (42, 'mamifero', 'Waterbuck, defassa', 30);
insert into mascotas (id, tipo, nombre, edad) values (43, 'ave', 'Porcupine, prehensile-tailed', 30);
insert into mascotas (id, tipo, nombre, edad) values (44, 'ave', 'Indian giant squirrel', 52);
insert into mascotas (id, tipo, nombre, edad) values (45, 'mamifero', 'Devil, tasmanian', 55);
insert into mascotas (id, tipo, nombre, edad) values (46, 'mamifero', 'Paca', 39);
insert into mascotas (id, tipo, nombre, edad) values (47, 'ave', 'Black-backed jackal', 59);
insert into mascotas (id, tipo, nombre, edad) values (48, 'mamifero', 'Wallaby, whip-tailed', 105);
insert into mascotas (id, tipo, nombre, edad) values (49, 'pez', 'Pelican, australian', 25);
insert into mascotas (id, tipo, nombre, edad) values (50, 'mamifero', 'Snow goose', 106);
insert into mascotas (id, tipo, nombre, edad) values (51, 'mamifero', 'Siskin, yellow-rumped', 76);
insert into mascotas (id, tipo, nombre, edad) values (52, 'ave', 'Bare-faced go away bird', 19);
insert into mascotas (id, tipo, nombre, edad) values (53, 'ave', 'Vulture, oriental white-backed', 109);
insert into mascotas (id, tipo, nombre, edad) values (54, 'mamifero', 'Black-fronted bulbul', 97);
insert into mascotas (id, tipo, nombre, edad) values (55, 'mamifero', 'White-bellied sea eagle', 61);
insert into mascotas (id, tipo, nombre, edad) values (56, 'ave', 'Cat, long-tailed spotted', 48);
insert into mascotas (id, tipo, nombre, edad) values (57, 'mamifero', 'Blue-tongued lizard', 29);
insert into mascotas (id, tipo, nombre, edad) values (58, 'mamifero', 'Stork, yellow-billed', 78);
insert into mascotas (id, tipo, nombre, edad) values (59, 'mamifero', 'Antelope ground squirrel', 76);
insert into mascotas (id, tipo, nombre, edad) values (60, 'mamifero', 'Purple grenadier', 100);
insert into mascotas (id, tipo, nombre, edad) values (61, 'ave', 'Little grebe', 49);
insert into mascotas (id, tipo, nombre, edad) values (62, 'ave', 'Chilean flamingo', 107);
insert into mascotas (id, tipo, nombre, edad) values (63, 'ave', 'Crow, house', 78);
insert into mascotas (id, tipo, nombre, edad) values (64, 'ave', 'Rattlesnake, horned', 25);
insert into mascotas (id, tipo, nombre, edad) values (65, 'mamifero', 'Macaw, scarlet', 70);
insert into mascotas (id, tipo, nombre, edad) values (66, 'mamifero', 'Common wombat', 47);
insert into mascotas (id, tipo, nombre, edad) values (67, 'mamifero', 'Squirrel, smith''s bush', 27);
insert into mascotas (id, tipo, nombre, edad) values (68, 'mamifero', 'Echidna, short-beaked', 106);
insert into mascotas (id, tipo, nombre, edad) values (69, 'pez', 'Scottish highland cow', 67);
insert into mascotas (id, tipo, nombre, edad) values (70, 'ave', 'Bushbaby, large-eared', 94);
insert into mascotas (id, tipo, nombre, edad) values (71, 'mamifero', 'Nelson ground squirrel', 83);
insert into mascotas (id, tipo, nombre, edad) values (72, 'ave', 'Wallaby, whip-tailed', 94);
insert into mascotas (id, tipo, nombre, edad) values (73, 'ave', 'Eastern grey kangaroo', 41);
insert into mascotas (id, tipo, nombre, edad) values (74, 'mamifero', 'Lizard, collared', 19);
insert into mascotas (id, tipo, nombre, edad) values (75, 'mamifero', 'Snow goose', 36);
insert into mascotas (id, tipo, nombre, edad) values (76, 'ave', 'Grey phalarope', 80);
insert into mascotas (id, tipo, nombre, edad) values (77, 'ave', 'Jackrabbit, white-tailed', 105);
insert into mascotas (id, tipo, nombre, edad) values (78, 'mamifero', 'Hawk-headed parrot', 81);
insert into mascotas (id, tipo, nombre, edad) values (79, 'mamifero', 'Kirk''s dik dik', 109);
insert into mascotas (id, tipo, nombre, edad) values (80, 'ave', 'Stick insect', 62);
insert into mascotas (id, tipo, nombre, edad) values (81, 'mamifero', 'Meerkat, red', 35);
insert into mascotas (id, tipo, nombre, edad) values (82, 'mamifero', 'Phascogale, brush-tailed', 53);
insert into mascotas (id, tipo, nombre, edad) values (83, 'pez', 'Sambar', 28);
insert into mascotas (id, tipo, nombre, edad) values (84, 'mamifero', 'Spotted deer', 106);
insert into mascotas (id, tipo, nombre, edad) values (85, 'mamifero', 'Screamer, crested', 52);
insert into mascotas (id, tipo, nombre, edad) values (86, 'mamifero', 'Marabou stork', 33);
insert into mascotas (id, tipo, nombre, edad) values (87, 'mamifero', 'Flicker, field', 93);
insert into mascotas (id, tipo, nombre, edad) values (88, 'ave', 'Long-tailed jaeger', 82);
insert into mascotas (id, tipo, nombre, edad) values (89, 'ave', 'Old world fruit bat (unidentified)', 109);
insert into mascotas (id, tipo, nombre, edad) values (90, 'mamifero', 'Bontebok', 34);
insert into mascotas (id, tipo, nombre, edad) values (91, 'ave', 'Mexican wolf', 102);
insert into mascotas (id, tipo, nombre, edad) values (92, 'pez', 'Ring-necked pheasant', 91);
insert into mascotas (id, tipo, nombre, edad) values (93, 'ave', 'Monkey, red howler', 78);
insert into mascotas (id, tipo, nombre, edad) values (94, 'pez', 'Pied kingfisher', 13);
insert into mascotas (id, tipo, nombre, edad) values (95, 'mamifero', 'Great egret', 77);
insert into mascotas (id, tipo, nombre, edad) values (96, 'mamifero', 'Common boubou shrike', 104);
insert into mascotas (id, tipo, nombre, edad) values (97, 'ave', 'Nuthatch, red-breasted', 58);
insert into mascotas (id, tipo, nombre, edad) values (98, 'ave', 'Duck, mountain', 62);
insert into mascotas (id, tipo, nombre, edad) values (99, 'pez', 'Yak', 63);
insert into mascotas (id, tipo, nombre, edad) values (100, 'mamifero', 'Two-toed tree sloth', 60);
insert into mascotas (id, tipo, nombre, edad) values (101, 'mamifero', 'Moose', 14);
insert into mascotas (id, tipo, nombre, edad) values (102, 'mamifero', 'Four-spotted skimmer', 84);
insert into mascotas (id, tipo, nombre, edad) values (103, 'ave', 'Water legaan', 39);
insert into mascotas (id, tipo, nombre, edad) values (104, 'pez', 'Rhea, gray', 35);
insert into mascotas (id, tipo, nombre, edad) values (105, 'mamifero', 'Brown pelican', 47);
insert into mascotas (id, tipo, nombre, edad) values (106, 'pez', 'Armadillo, seven-banded', 42);
insert into mascotas (id, tipo, nombre, edad) values (107, 'ave', 'Caracal', 108);
insert into mascotas (id, tipo, nombre, edad) values (108, 'ave', 'Carpet snake', 34);
insert into mascotas (id, tipo, nombre, edad) values (109, 'mamifero', 'Beaver, european', 82);
insert into mascotas (id, tipo, nombre, edad) values (110, 'ave', 'Waxbill, blue', 27);
insert into mascotas (id, tipo, nombre, edad) values (111, 'ave', 'Southern tamandua', 65);
insert into mascotas (id, tipo, nombre, edad) values (112, 'ave', 'Brazilian tapir', 12);
insert into mascotas (id, tipo, nombre, edad) values (113, 'ave', 'Ocelot', 71);
insert into mascotas (id, tipo, nombre, edad) values (114, 'mamifero', 'Indian mynah', 78);
insert into mascotas (id, tipo, nombre, edad) values (115, 'pez', 'Pied avocet', 38);
insert into mascotas (id, tipo, nombre, edad) values (116, 'mamifero', 'Black-crowned night heron', 89);
insert into mascotas (id, tipo, nombre, edad) values (117, 'mamifero', 'Red-winged blackbird', 46);
insert into mascotas (id, tipo, nombre, edad) values (118, 'ave', 'Bustard, kori', 12);
insert into mascotas (id, tipo, nombre, edad) values (119, 'mamifero', 'Possum, common brushtail', 62);
insert into mascotas (id, tipo, nombre, edad) values (120, 'ave', 'Boa, mexican', 45);
insert into mascotas (id, tipo, nombre, edad) values (121, 'mamifero', 'Legaan, ground', 90);
insert into mascotas (id, tipo, nombre, edad) values (122, 'mamifero', 'Lemming, arctic', 48);
insert into mascotas (id, tipo, nombre, edad) values (123, 'mamifero', 'Tawny eagle', 68);
insert into mascotas (id, tipo, nombre, edad) values (124, 'mamifero', 'Pademelon, red-legged', 19);
insert into mascotas (id, tipo, nombre, edad) values (125, 'ave', 'Nelson ground squirrel', 67);
insert into mascotas (id, tipo, nombre, edad) values (126, 'ave', 'Sportive lemur', 34);
insert into mascotas (id, tipo, nombre, edad) values (127, 'ave', 'Black-crowned night heron', 34);
insert into mascotas (id, tipo, nombre, edad) values (128, 'mamifero', 'Colobus, magistrate black', 100);
insert into mascotas (id, tipo, nombre, edad) values (129, 'ave', 'Common raccoon', 109);
insert into mascotas (id, tipo, nombre, edad) values (130, 'ave', 'White-winged dove', 96);
insert into mascotas (id, tipo, nombre, edad) values (131, 'mamifero', 'White-fronted capuchin', 43);
insert into mascotas (id, tipo, nombre, edad) values (132, 'mamifero', 'White-throated toucan', 88);
insert into mascotas (id, tipo, nombre, edad) values (133, 'ave', 'Red hartebeest', 65);
insert into mascotas (id, tipo, nombre, edad) values (134, 'mamifero', 'Otter, north american river', 97);
insert into mascotas (id, tipo, nombre, edad) values (135, 'mamifero', 'Sociable weaver', 106);
insert into mascotas (id, tipo, nombre, edad) values (136, 'ave', 'Fox, bat-eared', 22);
insert into mascotas (id, tipo, nombre, edad) values (137, 'mamifero', 'Argalis', 68);
insert into mascotas (id, tipo, nombre, edad) values (138, 'ave', 'Spur-winged goose', 45);
insert into mascotas (id, tipo, nombre, edad) values (139, 'mamifero', 'Burmese black mountain tortoise', 97);
insert into mascotas (id, tipo, nombre, edad) values (140, 'ave', 'Carmine bee-eater', 14);
insert into mascotas (id, tipo, nombre, edad) values (141, 'ave', 'Robin, white-throated', 18);
insert into mascotas (id, tipo, nombre, edad) values (142, 'mamifero', 'Bleu, red-cheeked cordon', 67);
insert into mascotas (id, tipo, nombre, edad) values (143, 'mamifero', 'Insect, stick', 98);
insert into mascotas (id, tipo, nombre, edad) values (144, 'mamifero', 'Squirrel, malabar', 101);
insert into mascotas (id, tipo, nombre, edad) values (145, 'mamifero', 'Godwit, hudsonian', 84);
insert into mascotas (id, tipo, nombre, edad) values (146, 'ave', 'Otter, african clawless', 72);
insert into mascotas (id, tipo, nombre, edad) values (147, 'ave', 'Eastern diamondback rattlesnake', 67);
insert into mascotas (id, tipo, nombre, edad) values (148, 'mamifero', 'Bird (unidentified)', 27);
insert into mascotas (id, tipo, nombre, edad) values (149, 'ave', 'Scarlet macaw', 49);
insert into mascotas (id, tipo, nombre, edad) values (150, 'pez', 'Lion, african', 88);
insert into mascotas (id, tipo, nombre, edad) values (151, 'ave', 'Wallaroo, common', 8);
insert into mascotas (id, tipo, nombre, edad) values (152, 'pez', 'Golden-mantled ground squirrel', 53);
insert into mascotas (id, tipo, nombre, edad) values (153, 'mamifero', 'Macaw, blue and gold', 64);
insert into mascotas (id, tipo, nombre, edad) values (154, 'ave', 'Beisa oryx', 77);
insert into mascotas (id, tipo, nombre, edad) values (155, 'pez', 'Three-banded plover', 81);
insert into mascotas (id, tipo, nombre, edad) values (156, 'ave', 'Whale, southern right', 10);
insert into mascotas (id, tipo, nombre, edad) values (157, 'ave', 'Trumpeter swan', 104);
insert into mascotas (id, tipo, nombre, edad) values (158, 'mamifero', 'White-rumped vulture', 92);
insert into mascotas (id, tipo, nombre, edad) values (159, 'mamifero', 'Bontebok', 94);
insert into mascotas (id, tipo, nombre, edad) values (160, 'pez', 'Peacock, blue', 28);
insert into mascotas (id, tipo, nombre, edad) values (161, 'mamifero', 'Anaconda (unidentified)', 79);
insert into mascotas (id, tipo, nombre, edad) values (162, 'ave', 'Osprey', 37);
insert into mascotas (id, tipo, nombre, edad) values (163, 'ave', 'Civet cat', 62);
insert into mascotas (id, tipo, nombre, edad) values (164, 'mamifero', 'Asian elephant', 22);
insert into mascotas (id, tipo, nombre, edad) values (165, 'mamifero', 'Spurfowl, yellow-necked', 106);
insert into mascotas (id, tipo, nombre, edad) values (166, 'ave', 'Blue wildebeest', 93);
insert into mascotas (id, tipo, nombre, edad) values (167, 'ave', 'Wambenger, red-tailed', 70);
insert into mascotas (id, tipo, nombre, edad) values (168, 'mamifero', 'Blue wildebeest', 92);
insert into mascotas (id, tipo, nombre, edad) values (169, 'mamifero', 'Great cormorant', 89);
insert into mascotas (id, tipo, nombre, edad) values (170, 'pez', 'Verreaux''s sifaka', 76);
insert into mascotas (id, tipo, nombre, edad) values (171, 'mamifero', 'Mynah, common', 48);
insert into mascotas (id, tipo, nombre, edad) values (172, 'mamifero', 'Cape raven', 72);
insert into mascotas (id, tipo, nombre, edad) values (173, 'mamifero', 'Goose, spur-winged', 63);
insert into mascotas (id, tipo, nombre, edad) values (174, 'ave', 'South African hedgehog', 79);
insert into mascotas (id, tipo, nombre, edad) values (175, 'mamifero', 'Butterfly, tropical buckeye', 26);
insert into mascotas (id, tipo, nombre, edad) values (176, 'pez', 'Small-spotted genet', 85);
insert into mascotas (id, tipo, nombre, edad) values (177, 'mamifero', 'Sheep, american bighorn', 33);
insert into mascotas (id, tipo, nombre, edad) values (178, 'ave', 'Civet, small-toothed palm', 58);
insert into mascotas (id, tipo, nombre, edad) values (179, 'pez', 'Shrike, common boubou', 27);
insert into mascotas (id, tipo, nombre, edad) values (180, 'ave', 'Small-spotted genet', 78);
insert into mascotas (id, tipo, nombre, edad) values (181, 'ave', 'Lion, south american sea', 32);
insert into mascotas (id, tipo, nombre, edad) values (182, 'ave', 'Impala', 51);
insert into mascotas (id, tipo, nombre, edad) values (183, 'mamifero', 'Golden-mantled ground squirrel', 29);
insert into mascotas (id, tipo, nombre, edad) values (184, 'mamifero', 'Spotted hyena', 79);
insert into mascotas (id, tipo, nombre, edad) values (185, 'ave', 'African porcupine', 57);
insert into mascotas (id, tipo, nombre, edad) values (186, 'ave', 'Python (unidentified)', 64);
insert into mascotas (id, tipo, nombre, edad) values (187, 'ave', 'Scaly-breasted lorikeet', 33);
insert into mascotas (id, tipo, nombre, edad) values (188, 'mamifero', 'Macaw, scarlet', 44);
insert into mascotas (id, tipo, nombre, edad) values (189, 'ave', 'White-eye, pale', 71);
insert into mascotas (id, tipo, nombre, edad) values (190, 'ave', 'White-fronted capuchin', 48);
insert into mascotas (id, tipo, nombre, edad) values (191, 'ave', 'Langur, gray', 104);
insert into mascotas (id, tipo, nombre, edad) values (192, 'mamifero', 'Lizard, giant girdled', 39);
insert into mascotas (id, tipo, nombre, edad) values (193, 'pez', 'Tsessebe', 63);
insert into mascotas (id, tipo, nombre, edad) values (194, 'mamifero', 'Waxbill, blue', 87);
insert into mascotas (id, tipo, nombre, edad) values (195, 'mamifero', 'Bird, secretary', 81);
insert into mascotas (id, tipo, nombre, edad) values (196, 'ave', 'Avocet, pied', 10);
insert into mascotas (id, tipo, nombre, edad) values (197, 'mamifero', 'Gazer, sun', 93);
insert into mascotas (id, tipo, nombre, edad) values (198, 'mamifero', 'Columbian rainbow boa', 47);
insert into mascotas (id, tipo, nombre, edad) values (199, 'mamifero', 'Gnu, brindled', 102);
insert into mascotas (id, tipo, nombre, edad) values (200, 'ave', 'Black rhinoceros', 24);
insert into mascotas (id, tipo, nombre, edad) values (201, 'mamifero', 'Swallow (unidentified)', 56);
insert into mascotas (id, tipo, nombre, edad) values (202, 'ave', 'Trotter, lily', 20);
insert into mascotas (id, tipo, nombre, edad) values (203, 'ave', 'Goldeneye, barrows', 109);
insert into mascotas (id, tipo, nombre, edad) values (204, 'mamifero', 'Glossy ibis', 81);
insert into mascotas (id, tipo, nombre, edad) values (205, 'mamifero', 'Nine-banded armadillo', 48);
insert into mascotas (id, tipo, nombre, edad) values (206, 'ave', 'Bushpig', 16);
insert into mascotas (id, tipo, nombre, edad) values (207, 'ave', 'Greater flamingo', 62);
insert into mascotas (id, tipo, nombre, edad) values (208, 'mamifero', 'Monitor, white-throated', 73);
insert into mascotas (id, tipo, nombre, edad) values (209, 'ave', 'Kangaroo, black-faced', 54);
insert into mascotas (id, tipo, nombre, edad) values (210, 'ave', 'Pacific gull', 97);
insert into mascotas (id, tipo, nombre, edad) values (211, 'mamifero', 'Palm squirrel', 81);
insert into mascotas (id, tipo, nombre, edad) values (212, 'ave', 'Black-eyed bulbul', 66);
insert into mascotas (id, tipo, nombre, edad) values (213, 'ave', 'Eastern white pelican', 101);
insert into mascotas (id, tipo, nombre, edad) values (214, 'mamifero', 'Blue-faced booby', 90);
insert into mascotas (id, tipo, nombre, edad) values (215, 'mamifero', 'Wild water buffalo', 41);
insert into mascotas (id, tipo, nombre, edad) values (216, 'mamifero', 'Glider, sugar', 86);
insert into mascotas (id, tipo, nombre, edad) values (217, 'ave', 'Southern right whale', 20);
insert into mascotas (id, tipo, nombre, edad) values (218, 'ave', 'Slender loris', 47);
insert into mascotas (id, tipo, nombre, edad) values (219, 'ave', 'Southern white-crowned shrike', 71);
insert into mascotas (id, tipo, nombre, edad) values (220, 'ave', 'Sifaka, verreaux''s', 102);
insert into mascotas (id, tipo, nombre, edad) values (221, 'pez', 'Burchell''s gonolek', 109);
insert into mascotas (id, tipo, nombre, edad) values (222, 'mamifero', 'Cobra, egyptian', 76);
insert into mascotas (id, tipo, nombre, edad) values (223, 'ave', 'Cat, ringtail', 20);
insert into mascotas (id, tipo, nombre, edad) values (224, 'ave', 'Goose, andean', 31);
insert into mascotas (id, tipo, nombre, edad) values (225, 'ave', 'Small-clawed otter', 76);
insert into mascotas (id, tipo, nombre, edad) values (226, 'mamifero', 'Crab-eating raccoon', 88);
insert into mascotas (id, tipo, nombre, edad) values (227, 'ave', 'Small Indian mongoose', 85);
insert into mascotas (id, tipo, nombre, edad) values (228, 'mamifero', 'Galah', 42);
insert into mascotas (id, tipo, nombre, edad) values (229, 'mamifero', 'Eagle, golden', 56);
insert into mascotas (id, tipo, nombre, edad) values (230, 'mamifero', 'Painted stork', 35);
insert into mascotas (id, tipo, nombre, edad) values (231, 'mamifero', 'Giraffe', 56);
insert into mascotas (id, tipo, nombre, edad) values (232, 'ave', 'Gull, pacific', 49);
insert into mascotas (id, tipo, nombre, edad) values (233, 'mamifero', 'Cat, african wild', 89);
insert into mascotas (id, tipo, nombre, edad) values (234, 'ave', 'Squirrel, antelope ground', 16);
insert into mascotas (id, tipo, nombre, edad) values (235, 'mamifero', 'Falcon, prairie', 109);
insert into mascotas (id, tipo, nombre, edad) values (236, 'ave', 'Common green iguana', 87);
insert into mascotas (id, tipo, nombre, edad) values (237, 'mamifero', 'Gila monster', 10);
insert into mascotas (id, tipo, nombre, edad) values (238, 'mamifero', 'Turaco, violet-crested', 95);
insert into mascotas (id, tipo, nombre, edad) values (239, 'mamifero', 'Southern black-backed gull', 57);
insert into mascotas (id, tipo, nombre, edad) values (240, 'ave', 'Nine-banded armadillo', 77);
insert into mascotas (id, tipo, nombre, edad) values (241, 'mamifero', 'Siskin, pine', 38);
insert into mascotas (id, tipo, nombre, edad) values (242, 'ave', 'Moorhen, purple', 41);
insert into mascotas (id, tipo, nombre, edad) values (243, 'ave', 'Baboon, yellow', 53);
insert into mascotas (id, tipo, nombre, edad) values (244, 'mamifero', 'Roller, lilac-breasted', 68);
insert into mascotas (id, tipo, nombre, edad) values (245, 'ave', 'Weaver, chestnut', 33);
insert into mascotas (id, tipo, nombre, edad) values (246, 'ave', 'Uinta ground squirrel', 88);
insert into mascotas (id, tipo, nombre, edad) values (247, 'mamifero', 'Buffalo, american', 35);
insert into mascotas (id, tipo, nombre, edad) values (248, 'ave', 'Royal tern', 36);
insert into mascotas (id, tipo, nombre, edad) values (249, 'mamifero', 'Boat-billed heron', 41);
insert into mascotas (id, tipo, nombre, edad) values (250, 'mamifero', 'Cat, jungle', 81);
insert into mascotas (id, tipo, nombre, edad) values (251, 'mamifero', 'Asian water dragon', 24);
insert into mascotas (id, tipo, nombre, edad) values (252, 'ave', 'Squirrel, pine', 70);
insert into mascotas (id, tipo, nombre, edad) values (253, 'ave', 'Clark''s nutcracker', 20);
insert into mascotas (id, tipo, nombre, edad) values (254, 'mamifero', 'Zebra, plains', 19);
insert into mascotas (id, tipo, nombre, edad) values (255, 'pez', 'Heron, yellow-crowned night', 15);
insert into mascotas (id, tipo, nombre, edad) values (256, 'mamifero', 'Salmon pink bird eater tarantula', 104);
insert into mascotas (id, tipo, nombre, edad) values (257, 'mamifero', 'Arboral spiny rat', 93);
insert into mascotas (id, tipo, nombre, edad) values (258, 'mamifero', 'Dabchick', 19);
insert into mascotas (id, tipo, nombre, edad) values (259, 'ave', 'Crane, sandhill', 36);
insert into mascotas (id, tipo, nombre, edad) values (260, 'ave', 'Butterfly, canadian tiger swallowtail', 53);
insert into mascotas (id, tipo, nombre, edad) values (261, 'mamifero', 'Crested screamer', 65);
insert into mascotas (id, tipo, nombre, edad) values (262, 'ave', 'Gerbil (unidentified)', 40);
insert into mascotas (id, tipo, nombre, edad) values (263, 'mamifero', 'Caracara (unidentified)', 93);
insert into mascotas (id, tipo, nombre, edad) values (264, 'ave', 'Weaver, sociable', 85);
insert into mascotas (id, tipo, nombre, edad) values (265, 'mamifero', 'Galapagos hawk', 96);
insert into mascotas (id, tipo, nombre, edad) values (266, 'mamifero', 'Blackish oystercatcher', 65);
insert into mascotas (id, tipo, nombre, edad) values (267, 'ave', 'Crowned eagle', 102);
insert into mascotas (id, tipo, nombre, edad) values (268, 'mamifero', 'Vulture, black', 38);
insert into mascotas (id, tipo, nombre, edad) values (269, 'ave', 'Buttermilk snake', 29);
insert into mascotas (id, tipo, nombre, edad) values (270, 'ave', 'Macaw, blue and gold', 18);
insert into mascotas (id, tipo, nombre, edad) values (271, 'ave', 'Skunk, western spotted', 92);
insert into mascotas (id, tipo, nombre, edad) values (272, 'pez', 'Toucan, red-billed', 98);
insert into mascotas (id, tipo, nombre, edad) values (273, 'ave', 'Crab, red lava', 28);
insert into mascotas (id, tipo, nombre, edad) values (274, 'ave', 'Otter, oriental short-clawed', 104);
insert into mascotas (id, tipo, nombre, edad) values (275, 'mamifero', 'Moccasin, water', 88);
insert into mascotas (id, tipo, nombre, edad) values (276, 'mamifero', 'Secretary bird', 97);
insert into mascotas (id, tipo, nombre, edad) values (277, 'mamifero', 'Bushbuck', 108);
insert into mascotas (id, tipo, nombre, edad) values (278, 'ave', 'Robin, white-throated', 63);
insert into mascotas (id, tipo, nombre, edad) values (279, 'mamifero', 'Southern brown bandicoot', 107);
insert into mascotas (id, tipo, nombre, edad) values (280, 'ave', 'Genet, small-spotted', 81);
insert into mascotas (id, tipo, nombre, edad) values (281, 'ave', 'Civet, common palm', 55);
insert into mascotas (id, tipo, nombre, edad) values (282, 'ave', 'Giant armadillo', 83);
insert into mascotas (id, tipo, nombre, edad) values (283, 'mamifero', 'Desert spiny lizard', 24);
insert into mascotas (id, tipo, nombre, edad) values (284, 'mamifero', 'Kaffir cat', 46);
insert into mascotas (id, tipo, nombre, edad) values (285, 'ave', 'Otter, cape clawless', 23);
insert into mascotas (id, tipo, nombre, edad) values (286, 'mamifero', 'African polecat', 101);
insert into mascotas (id, tipo, nombre, edad) values (287, 'ave', 'Bustard, kori', 27);
insert into mascotas (id, tipo, nombre, edad) values (288, 'ave', 'American marten', 26);
insert into mascotas (id, tipo, nombre, edad) values (289, 'ave', 'Echidna, short-beaked', 104);
insert into mascotas (id, tipo, nombre, edad) values (290, 'mamifero', 'Pintail, bahama', 87);
insert into mascotas (id, tipo, nombre, edad) values (291, 'pez', 'Gray heron', 50);
insert into mascotas (id, tipo, nombre, edad) values (292, 'mamifero', 'Tammar wallaby', 59);
insert into mascotas (id, tipo, nombre, edad) values (293, 'ave', 'Bush dog', 95);
insert into mascotas (id, tipo, nombre, edad) values (294, 'ave', 'Swan, black', 72);
insert into mascotas (id, tipo, nombre, edad) values (295, 'ave', 'Dragon, frilled', 27);
insert into mascotas (id, tipo, nombre, edad) values (296, 'mamifero', 'Goanna lizard', 88);
insert into mascotas (id, tipo, nombre, edad) values (297, 'mamifero', 'Indian porcupine', 13);
insert into mascotas (id, tipo, nombre, edad) values (298, 'ave', 'Bear, grizzly', 22);
insert into mascotas (id, tipo, nombre, edad) values (299, 'ave', 'Seven-banded armadillo', 84);
insert into mascotas (id, tipo, nombre, edad) values (300, 'pez', 'Trumpeter, dark-winged', 95);
insert into mascotas (id, tipo, nombre, edad) values (301, 'ave', 'Striped dolphin', 55);
insert into mascotas (id, tipo, nombre, edad) values (302, 'ave', 'Red hartebeest', 54);
insert into mascotas (id, tipo, nombre, edad) values (303, 'ave', 'White-rumped vulture', 68);
insert into mascotas (id, tipo, nombre, edad) values (304, 'ave', 'Glossy ibis', 12);
insert into mascotas (id, tipo, nombre, edad) values (305, 'mamifero', 'Savanna fox', 87);
insert into mascotas (id, tipo, nombre, edad) values (306, 'ave', 'Giant heron', 37);
insert into mascotas (id, tipo, nombre, edad) values (307, 'mamifero', 'Marine iguana', 12);
insert into mascotas (id, tipo, nombre, edad) values (308, 'mamifero', 'Glider, sugar', 54);
insert into mascotas (id, tipo, nombre, edad) values (309, 'ave', 'Racer, american', 52);
insert into mascotas (id, tipo, nombre, edad) values (310, 'ave', 'Tyrant flycatcher', 62);
insert into mascotas (id, tipo, nombre, edad) values (311, 'mamifero', 'Eastern quoll', 56);
insert into mascotas (id, tipo, nombre, edad) values (312, 'ave', 'Brush-tailed bettong', 48);
insert into mascotas (id, tipo, nombre, edad) values (313, 'mamifero', 'Buttermilk snake', 103);
insert into mascotas (id, tipo, nombre, edad) values (314, 'pez', 'Black-winged stilt', 60);
insert into mascotas (id, tipo, nombre, edad) values (315, 'ave', 'California sea lion', 35);
insert into mascotas (id, tipo, nombre, edad) values (316, 'ave', 'Crow, house', 60);
insert into mascotas (id, tipo, nombre, edad) values (317, 'pez', 'Buffalo, wild water', 99);
insert into mascotas (id, tipo, nombre, edad) values (318, 'mamifero', 'Gerbil (unidentified)', 66);
insert into mascotas (id, tipo, nombre, edad) values (319, 'pez', 'Bulbul, black-fronted', 74);
insert into mascotas (id, tipo, nombre, edad) values (320, 'mamifero', 'Stick insect', 51);
insert into mascotas (id, tipo, nombre, edad) values (321, 'ave', 'Mockingbird, galapagos', 16);
insert into mascotas (id, tipo, nombre, edad) values (322, 'ave', 'Cape wild cat', 79);
insert into mascotas (id, tipo, nombre, edad) values (323, 'mamifero', 'Hippopotamus', 66);
insert into mascotas (id, tipo, nombre, edad) values (324, 'mamifero', 'Owl, great horned', 85);
insert into mascotas (id, tipo, nombre, edad) values (325, 'mamifero', 'Pied cormorant', 46);
insert into mascotas (id, tipo, nombre, edad) values (326, 'mamifero', 'Horned lark', 97);
insert into mascotas (id, tipo, nombre, edad) values (327, 'ave', 'Monkey, red howler', 75);
insert into mascotas (id, tipo, nombre, edad) values (328, 'ave', 'Dragon, western bearded', 27);
insert into mascotas (id, tipo, nombre, edad) values (329, 'mamifero', 'African black crake', 90);
insert into mascotas (id, tipo, nombre, edad) values (330, 'pez', 'Corella, long-billed', 33);
insert into mascotas (id, tipo, nombre, edad) values (331, 'mamifero', 'Siskin, pine', 16);
insert into mascotas (id, tipo, nombre, edad) values (332, 'mamifero', 'Eastern indigo snake', 47);
insert into mascotas (id, tipo, nombre, edad) values (333, 'ave', 'Jabiru stork', 32);
insert into mascotas (id, tipo, nombre, edad) values (334, 'ave', 'Australian pelican', 40);
insert into mascotas (id, tipo, nombre, edad) values (335, 'mamifero', 'White-fronted capuchin', 19);
insert into mascotas (id, tipo, nombre, edad) values (336, 'pez', 'Sandgrouse, yellow-throated', 59);
insert into mascotas (id, tipo, nombre, edad) values (337, 'mamifero', 'Hippopotamus', 108);
insert into mascotas (id, tipo, nombre, edad) values (338, 'ave', 'Trotter, lily', 39);
insert into mascotas (id, tipo, nombre, edad) values (339, 'ave', 'Roller, lilac-breasted', 58);
insert into mascotas (id, tipo, nombre, edad) values (340, 'mamifero', 'Bird, black-throated butcher', 20);
insert into mascotas (id, tipo, nombre, edad) values (341, 'pez', 'Jabiru stork', 62);
insert into mascotas (id, tipo, nombre, edad) values (342, 'mamifero', 'Paddy heron (unidentified)', 9);
insert into mascotas (id, tipo, nombre, edad) values (343, 'ave', 'Phalarope, northern', 29);
insert into mascotas (id, tipo, nombre, edad) values (344, 'ave', 'Glossy starling (unidentified)', 40);
insert into mascotas (id, tipo, nombre, edad) values (345, 'mamifero', 'Comb duck', 50);
insert into mascotas (id, tipo, nombre, edad) values (346, 'mamifero', 'Columbian rainbow boa', 30);
insert into mascotas (id, tipo, nombre, edad) values (347, 'mamifero', 'Macaque, japanese', 39);
insert into mascotas (id, tipo, nombre, edad) values (348, 'pez', 'South American sea lion', 79);
insert into mascotas (id, tipo, nombre, edad) values (349, 'mamifero', 'Mexican wolf', 94);
insert into mascotas (id, tipo, nombre, edad) values (350, 'mamifero', 'Blacksmith plover', 82);
insert into mascotas (id, tipo, nombre, edad) values (351, 'mamifero', 'Bat, asian false vampire', 109);
insert into mascotas (id, tipo, nombre, edad) values (352, 'pez', 'Short-beaked echidna', 16);
insert into mascotas (id, tipo, nombre, edad) values (353, 'mamifero', 'Bee-eater (unidentified)', 50);
insert into mascotas (id, tipo, nombre, edad) values (354, 'ave', 'Red-tailed hawk', 13);
insert into mascotas (id, tipo, nombre, edad) values (355, 'ave', 'House crow', 31);
insert into mascotas (id, tipo, nombre, edad) values (356, 'ave', 'Gull, swallow-tail', 55);
insert into mascotas (id, tipo, nombre, edad) values (357, 'mamifero', 'Steenbok', 19);
insert into mascotas (id, tipo, nombre, edad) values (358, 'mamifero', 'Japanese macaque', 78);
insert into mascotas (id, tipo, nombre, edad) values (359, 'mamifero', 'Goldeneye, barrows', 86);
insert into mascotas (id, tipo, nombre, edad) values (360, 'mamifero', 'Stork, jabiru', 68);
insert into mascotas (id, tipo, nombre, edad) values (361, 'mamifero', 'Ferruginous hawk', 31);
insert into mascotas (id, tipo, nombre, edad) values (362, 'ave', 'Ringtail, common', 29);
insert into mascotas (id, tipo, nombre, edad) values (363, 'ave', 'Turkey, australian brush', 37);
insert into mascotas (id, tipo, nombre, edad) values (364, 'ave', 'Common zorro', 26);
insert into mascotas (id, tipo, nombre, edad) values (365, 'mamifero', 'Purple moorhen', 92);
insert into mascotas (id, tipo, nombre, edad) values (366, 'ave', 'White rhinoceros', 19);
insert into mascotas (id, tipo, nombre, edad) values (367, 'mamifero', 'Gazelle, thomson''s', 80);
insert into mascotas (id, tipo, nombre, edad) values (368, 'mamifero', 'Kiskadee, great', 100);
insert into mascotas (id, tipo, nombre, edad) values (369, 'mamifero', 'Crane, stanley', 99);
insert into mascotas (id, tipo, nombre, edad) values (370, 'ave', 'Cat, miner''s', 28);
insert into mascotas (id, tipo, nombre, edad) values (371, 'ave', 'White-winged dove', 67);
insert into mascotas (id, tipo, nombre, edad) values (372, 'ave', 'Owl, great horned', 15);
insert into mascotas (id, tipo, nombre, edad) values (373, 'ave', 'Boa, malagasy ground', 97);
insert into mascotas (id, tipo, nombre, edad) values (374, 'ave', 'Tortoise, radiated', 56);
insert into mascotas (id, tipo, nombre, edad) values (375, 'mamifero', 'Coke''s hartebeest', 54);
insert into mascotas (id, tipo, nombre, edad) values (376, 'mamifero', 'Plains zebra', 20);
insert into mascotas (id, tipo, nombre, edad) values (377, 'mamifero', 'Stone sheep', 34);
insert into mascotas (id, tipo, nombre, edad) values (378, 'pez', 'Snake, green vine', 62);
insert into mascotas (id, tipo, nombre, edad) values (379, 'mamifero', 'Macaw, green-winged', 46);
insert into mascotas (id, tipo, nombre, edad) values (380, 'ave', 'Agile wallaby', 90);
insert into mascotas (id, tipo, nombre, edad) values (381, 'ave', 'Tortoise, galapagos', 102);
insert into mascotas (id, tipo, nombre, edad) values (382, 'ave', 'Owl, snowy', 25);
insert into mascotas (id, tipo, nombre, edad) values (383, 'pez', 'Deer, roe', 73);
insert into mascotas (id, tipo, nombre, edad) values (384, 'ave', 'Pocket gopher (unidentified)', 95);
insert into mascotas (id, tipo, nombre, edad) values (385, 'ave', 'Cat, jungle', 85);
insert into mascotas (id, tipo, nombre, edad) values (386, 'mamifero', 'Red-headed woodpecker', 31);
insert into mascotas (id, tipo, nombre, edad) values (387, 'mamifero', 'Iguana, common green', 32);
insert into mascotas (id, tipo, nombre, edad) values (388, 'ave', 'Gull, kelp', 28);
insert into mascotas (id, tipo, nombre, edad) values (389, 'mamifero', 'Bear, polar', 36);
insert into mascotas (id, tipo, nombre, edad) values (390, 'ave', 'Large cormorant', 12);
insert into mascotas (id, tipo, nombre, edad) values (391, 'ave', 'Eagle, golden', 89);
insert into mascotas (id, tipo, nombre, edad) values (392, 'mamifero', 'Goldeneye, barrows', 99);
insert into mascotas (id, tipo, nombre, edad) values (393, 'pez', 'Scaly-breasted lorikeet', 40);
insert into mascotas (id, tipo, nombre, edad) values (394, 'mamifero', 'Egyptian viper', 102);
insert into mascotas (id, tipo, nombre, edad) values (395, 'ave', 'Duck, blue', 61);
insert into mascotas (id, tipo, nombre, edad) values (396, 'ave', 'Common eland', 17);
insert into mascotas (id, tipo, nombre, edad) values (397, 'ave', 'Hippopotamus', 43);
insert into mascotas (id, tipo, nombre, edad) values (398, 'mamifero', 'Armadillo, nine-banded', 74);
insert into mascotas (id, tipo, nombre, edad) values (399, 'ave', 'Ass, asiatic wild', 50);
insert into mascotas (id, tipo, nombre, edad) values (400, 'ave', 'Yellow-throated sandgrouse', 56);
insert into mascotas (id, tipo, nombre, edad) values (401, 'ave', 'Red phalarope', 72);
insert into mascotas (id, tipo, nombre, edad) values (402, 'ave', 'Pine snake (unidentified)', 76);
insert into mascotas (id, tipo, nombre, edad) values (403, 'ave', 'Black-crowned crane', 48);
insert into mascotas (id, tipo, nombre, edad) values (404, 'ave', 'Weaver, chestnut', 95);
insert into mascotas (id, tipo, nombre, edad) values (405, 'ave', 'Baboon, savanna', 74);
insert into mascotas (id, tipo, nombre, edad) values (406, 'mamifero', 'Hoopoe, eurasian', 50);
insert into mascotas (id, tipo, nombre, edad) values (407, 'mamifero', 'Lizard, giant girdled', 106);
insert into mascotas (id, tipo, nombre, edad) values (408, 'mamifero', 'Gerbil (unidentified)', 47);
insert into mascotas (id, tipo, nombre, edad) values (409, 'ave', 'Snow goose', 53);
insert into mascotas (id, tipo, nombre, edad) values (410, 'ave', 'Bleeding heart monkey', 30);
insert into mascotas (id, tipo, nombre, edad) values (411, 'mamifero', 'Southern elephant seal', 92);
insert into mascotas (id, tipo, nombre, edad) values (412, 'ave', 'Tortoise, burmese brown mountain', 66);
insert into mascotas (id, tipo, nombre, edad) values (413, 'ave', 'Burrowing owl', 78);
insert into mascotas (id, tipo, nombre, edad) values (414, 'ave', 'Turtle, eastern box', 69);
insert into mascotas (id, tipo, nombre, edad) values (415, 'mamifero', 'Polecat, african', 37);
insert into mascotas (id, tipo, nombre, edad) values (416, 'mamifero', 'Leopard', 85);
insert into mascotas (id, tipo, nombre, edad) values (417, 'mamifero', 'Asiatic wild ass', 58);
insert into mascotas (id, tipo, nombre, edad) values (418, 'ave', 'Dog, bush', 33);
insert into mascotas (id, tipo, nombre, edad) values (419, 'ave', 'Ferret, black-footed', 79);
insert into mascotas (id, tipo, nombre, edad) values (420, 'mamifero', 'Oystercatcher, blackish', 80);
insert into mascotas (id, tipo, nombre, edad) values (421, 'mamifero', 'Partridge, coqui', 49);
insert into mascotas (id, tipo, nombre, edad) values (422, 'mamifero', 'African black crake', 41);
insert into mascotas (id, tipo, nombre, edad) values (423, 'ave', 'Brolga crane', 58);
insert into mascotas (id, tipo, nombre, edad) values (424, 'ave', 'Bald eagle', 22);
insert into mascotas (id, tipo, nombre, edad) values (425, 'mamifero', 'Squirrel, smith''s bush', 77);
insert into mascotas (id, tipo, nombre, edad) values (426, 'ave', 'Turkey, wild', 108);
insert into mascotas (id, tipo, nombre, edad) values (427, 'mamifero', 'Adouri (unidentified)', 24);
insert into mascotas (id, tipo, nombre, edad) values (428, 'ave', 'Southern tamandua', 66);
insert into mascotas (id, tipo, nombre, edad) values (429, 'pez', 'Cormorant, flightless', 66);
insert into mascotas (id, tipo, nombre, edad) values (430, 'ave', 'Dragon, asian water', 16);
insert into mascotas (id, tipo, nombre, edad) values (431, 'ave', 'Hawk, ferruginous', 37);
insert into mascotas (id, tipo, nombre, edad) values (432, 'ave', 'Common raccoon', 57);
insert into mascotas (id, tipo, nombre, edad) values (433, 'ave', 'European wild cat', 91);
insert into mascotas (id, tipo, nombre, edad) values (434, 'ave', 'Hare, arctic', 49);
insert into mascotas (id, tipo, nombre, edad) values (435, 'mamifero', 'Crane, sandhill', 89);
insert into mascotas (id, tipo, nombre, edad) values (436, 'ave', 'Spider, wolf', 53);
insert into mascotas (id, tipo, nombre, edad) values (437, 'pez', 'Monkey, red howler', 96);
insert into mascotas (id, tipo, nombre, edad) values (438, 'mamifero', 'Canadian river otter', 30);
insert into mascotas (id, tipo, nombre, edad) values (439, 'mamifero', 'Crane, sandhill', 15);
insert into mascotas (id, tipo, nombre, edad) values (440, 'mamifero', 'Lapwing (unidentified)', 59);
insert into mascotas (id, tipo, nombre, edad) values (441, 'mamifero', 'Blesbok', 93);
insert into mascotas (id, tipo, nombre, edad) values (442, 'mamifero', 'Goanna lizard', 13);
insert into mascotas (id, tipo, nombre, edad) values (443, 'mamifero', 'Crab-eating raccoon', 108);
insert into mascotas (id, tipo, nombre, edad) values (444, 'ave', 'Eastern diamondback rattlesnake', 39);
insert into mascotas (id, tipo, nombre, edad) values (445, 'pez', 'Carmine bee-eater', 106);
insert into mascotas (id, tipo, nombre, edad) values (446, 'ave', 'Boar, wild', 41);
insert into mascotas (id, tipo, nombre, edad) values (447, 'ave', 'Coqui partridge', 63);
insert into mascotas (id, tipo, nombre, edad) values (448, 'ave', 'Gulls (unidentified)', 96);
insert into mascotas (id, tipo, nombre, edad) values (449, 'ave', 'Puna ibis', 12);
insert into mascotas (id, tipo, nombre, edad) values (450, 'mamifero', 'Goose, egyptian', 42);
insert into mascotas (id, tipo, nombre, edad) values (451, 'mamifero', 'Western bearded dragon', 16);
insert into mascotas (id, tipo, nombre, edad) values (452, 'mamifero', 'Tortoise, galapagos', 14);
insert into mascotas (id, tipo, nombre, edad) values (453, 'mamifero', 'Baboon, savanna', 70);
insert into mascotas (id, tipo, nombre, edad) values (454, 'mamifero', 'Coatimundi, ring-tailed', 90);
insert into mascotas (id, tipo, nombre, edad) values (455, 'ave', 'Ibis, glossy', 34);
insert into mascotas (id, tipo, nombre, edad) values (456, 'mamifero', 'Tortoise, burmese black mountain', 105);
insert into mascotas (id, tipo, nombre, edad) values (457, 'mamifero', 'Lizard, collared', 87);
insert into mascotas (id, tipo, nombre, edad) values (458, 'mamifero', 'White-winged dove', 44);
insert into mascotas (id, tipo, nombre, edad) values (459, 'mamifero', 'Egret, cattle', 59);
insert into mascotas (id, tipo, nombre, edad) values (460, 'ave', 'Pelican, eastern white', 68);
insert into mascotas (id, tipo, nombre, edad) values (461, 'mamifero', 'Black and white colobus', 79);
insert into mascotas (id, tipo, nombre, edad) values (462, 'ave', 'Silver gull', 57);
insert into mascotas (id, tipo, nombre, edad) values (463, 'ave', 'Common seal', 41);
insert into mascotas (id, tipo, nombre, edad) values (464, 'pez', 'Wallaby, tammar', 57);
insert into mascotas (id, tipo, nombre, edad) values (465, 'mamifero', 'Possum, golden brush-tailed', 83);
insert into mascotas (id, tipo, nombre, edad) values (466, 'ave', 'Gorilla, western lowland', 44);
insert into mascotas (id, tipo, nombre, edad) values (467, 'ave', 'Honey badger', 30);
insert into mascotas (id, tipo, nombre, edad) values (468, 'mamifero', 'Common brushtail possum', 51);
insert into mascotas (id, tipo, nombre, edad) values (469, 'mamifero', 'Serval', 38);
insert into mascotas (id, tipo, nombre, edad) values (470, 'ave', 'Lapwing, southern', 58);
insert into mascotas (id, tipo, nombre, edad) values (471, 'mamifero', 'African ground squirrel (unidentified)', 87);
insert into mascotas (id, tipo, nombre, edad) values (472, 'mamifero', 'Owl, madagascar hawk', 27);
insert into mascotas (id, tipo, nombre, edad) values (473, 'mamifero', 'Ibis, glossy', 102);
insert into mascotas (id, tipo, nombre, edad) values (474, 'mamifero', 'Eastern quoll', 26);
insert into mascotas (id, tipo, nombre, edad) values (475, 'mamifero', 'Otter, cape clawless', 49);
insert into mascotas (id, tipo, nombre, edad) values (476, 'ave', 'Darwin ground finch (unidentified)', 10);
insert into mascotas (id, tipo, nombre, edad) values (477, 'ave', 'Red-tailed hawk', 106);
insert into mascotas (id, tipo, nombre, edad) values (478, 'ave', 'White-throated robin', 54);
insert into mascotas (id, tipo, nombre, edad) values (479, 'mamifero', 'Squirrel, golden-mantled ground', 55);
insert into mascotas (id, tipo, nombre, edad) values (480, 'mamifero', 'Numbat', 85);
insert into mascotas (id, tipo, nombre, edad) values (481, 'ave', 'Coke''s hartebeest', 41);
insert into mascotas (id, tipo, nombre, edad) values (482, 'ave', 'Snowy owl', 77);
insert into mascotas (id, tipo, nombre, edad) values (483, 'pez', 'Roe deer', 20);
insert into mascotas (id, tipo, nombre, edad) values (484, 'mamifero', 'Australian masked owl', 54);
insert into mascotas (id, tipo, nombre, edad) values (485, 'mamifero', 'Spotted-tailed quoll', 11);
insert into mascotas (id, tipo, nombre, edad) values (486, 'mamifero', 'Bohor reedbuck', 44);
insert into mascotas (id, tipo, nombre, edad) values (487, 'ave', 'Savanna baboon', 67);
insert into mascotas (id, tipo, nombre, edad) values (488, 'mamifero', 'Flamingo, lesser', 109);
insert into mascotas (id, tipo, nombre, edad) values (489, 'mamifero', 'Squirrel, grey-footed', 88);
insert into mascotas (id, tipo, nombre, edad) values (490, 'mamifero', 'Spotted wood sandpiper', 18);
insert into mascotas (id, tipo, nombre, edad) values (491, 'mamifero', 'Hornbill, leadbeateri''s ground', 13);
insert into mascotas (id, tipo, nombre, edad) values (492, 'ave', 'Southern brown bandicoot', 81);
insert into mascotas (id, tipo, nombre, edad) values (493, 'mamifero', 'Black bear', 38);
insert into mascotas (id, tipo, nombre, edad) values (494, 'ave', 'Asiatic jackal', 105);
insert into mascotas (id, tipo, nombre, edad) values (495, 'pez', 'Mongoose, banded', 45);
insert into mascotas (id, tipo, nombre, edad) values (496, 'mamifero', 'Puma', 15);
insert into mascotas (id, tipo, nombre, edad) values (497, 'ave', 'Asian red fox', 70);
insert into mascotas (id, tipo, nombre, edad) values (498, 'mamifero', 'Possum, pygmy', 12);
insert into mascotas (id, tipo, nombre, edad) values (499, 'ave', 'Mongoose, banded', 14);
insert into mascotas (id, tipo, nombre, edad) values (500, 'mamifero', 'Four-horned antelope', 86);
insert into mascotas (id, tipo, nombre, edad) values (501, 'ave', 'Squirrel, uinta ground', 77);
insert into mascotas (id, tipo, nombre, edad) values (502, 'mamifero', 'Wallaby, river', 11);
insert into mascotas (id, tipo, nombre, edad) values (503, 'mamifero', 'Tortoise, galapagos', 70);
insert into mascotas (id, tipo, nombre, edad) values (504, 'mamifero', 'Eagle owl (unidentified)', 64);
insert into mascotas (id, tipo, nombre, edad) values (505, 'ave', 'Hawk, galapagos', 80);
insert into mascotas (id, tipo, nombre, edad) values (506, 'ave', 'Deer, savannah', 47);
insert into mascotas (id, tipo, nombre, edad) values (507, 'ave', 'Anaconda (unidentified)', 24);
insert into mascotas (id, tipo, nombre, edad) values (508, 'ave', 'Gecko, bent-toed', 55);
insert into mascotas (id, tipo, nombre, edad) values (509, 'ave', 'Numbat', 54);
insert into mascotas (id, tipo, nombre, edad) values (510, 'mamifero', 'Skimmer, four-spotted', 106);
insert into mascotas (id, tipo, nombre, edad) values (511, 'mamifero', 'Deer, black-tailed', 83);
insert into mascotas (id, tipo, nombre, edad) values (512, 'pez', 'Swamp deer', 51);
insert into mascotas (id, tipo, nombre, edad) values (513, 'mamifero', 'Cobra, cape', 84);
insert into mascotas (id, tipo, nombre, edad) values (514, 'mamifero', 'Egyptian viper', 48);
insert into mascotas (id, tipo, nombre, edad) values (515, 'ave', 'Cape clawless otter', 90);
insert into mascotas (id, tipo, nombre, edad) values (516, 'ave', 'Flightless cormorant', 69);
insert into mascotas (id, tipo, nombre, edad) values (517, 'ave', 'Snow goose', 66);
insert into mascotas (id, tipo, nombre, edad) values (518, 'mamifero', 'Antelope, four-horned', 79);
insert into mascotas (id, tipo, nombre, edad) values (519, 'ave', 'Asian water dragon', 32);
insert into mascotas (id, tipo, nombre, edad) values (520, 'mamifero', 'Turtle, long-necked', 65);
insert into mascotas (id, tipo, nombre, edad) values (521, 'mamifero', 'Swamp deer', 42);
insert into mascotas (id, tipo, nombre, edad) values (522, 'mamifero', 'Tenrec, tailless', 24);
insert into mascotas (id, tipo, nombre, edad) values (523, 'ave', 'Raccoon, crab-eating', 69);
insert into mascotas (id, tipo, nombre, edad) values (524, 'mamifero', 'Sun gazer', 48);
insert into mascotas (id, tipo, nombre, edad) values (525, 'ave', 'Stork, black-necked', 46);
insert into mascotas (id, tipo, nombre, edad) values (526, 'ave', 'Salmon, sockeye', 60);
insert into mascotas (id, tipo, nombre, edad) values (527, 'mamifero', 'Secretary bird', 14);
insert into mascotas (id, tipo, nombre, edad) values (528, 'ave', 'Rattlesnake, dusky', 82);
insert into mascotas (id, tipo, nombre, edad) values (529, 'ave', 'Squirrel, grey-footed', 47);
insert into mascotas (id, tipo, nombre, edad) values (530, 'ave', 'Pheasant, common', 106);
insert into mascotas (id, tipo, nombre, edad) values (531, 'mamifero', 'Turtle, eastern box', 54);
insert into mascotas (id, tipo, nombre, edad) values (532, 'ave', 'Rhesus macaque', 43);
insert into mascotas (id, tipo, nombre, edad) values (533, 'ave', 'Pallas''s fish eagle', 58);
insert into mascotas (id, tipo, nombre, edad) values (534, 'ave', 'Robin, kalahari scrub', 64);
insert into mascotas (id, tipo, nombre, edad) values (535, 'mamifero', 'Waxbill, blue', 96);
insert into mascotas (id, tipo, nombre, edad) values (536, 'ave', 'Common eland', 66);
insert into mascotas (id, tipo, nombre, edad) values (537, 'mamifero', 'Armadillo, seven-banded', 24);
insert into mascotas (id, tipo, nombre, edad) values (538, 'ave', 'Grouse, greater sage', 55);
insert into mascotas (id, tipo, nombre, edad) values (539, 'ave', 'Cuis', 69);
insert into mascotas (id, tipo, nombre, edad) values (540, 'ave', 'Burchell''s gonolek', 39);
insert into mascotas (id, tipo, nombre, edad) values (541, 'mamifero', 'Snake, green vine', 47);
insert into mascotas (id, tipo, nombre, edad) values (542, 'pez', 'Stanley bustard', 40);
insert into mascotas (id, tipo, nombre, edad) values (543, 'mamifero', 'African porcupine', 101);
insert into mascotas (id, tipo, nombre, edad) values (544, 'pez', 'Chickadee, black-capped', 57);
insert into mascotas (id, tipo, nombre, edad) values (545, 'ave', 'Cape starling', 79);
insert into mascotas (id, tipo, nombre, edad) values (546, 'mamifero', 'Phascogale, red-tailed', 88);
insert into mascotas (id, tipo, nombre, edad) values (547, 'ave', 'Long-tailed spotted cat', 61);
insert into mascotas (id, tipo, nombre, edad) values (548, 'ave', 'Stork, black-necked', 75);
insert into mascotas (id, tipo, nombre, edad) values (549, 'mamifero', 'Steenbok', 61);
insert into mascotas (id, tipo, nombre, edad) values (550, 'ave', 'Lilac-breasted roller', 59);
insert into mascotas (id, tipo, nombre, edad) values (551, 'ave', 'Lizard, frilled', 18);
insert into mascotas (id, tipo, nombre, edad) values (552, 'mamifero', 'Trumpeter swan', 20);
insert into mascotas (id, tipo, nombre, edad) values (553, 'mamifero', 'Fringe-eared oryx', 75);
insert into mascotas (id, tipo, nombre, edad) values (554, 'mamifero', 'Dove, ring', 77);
insert into mascotas (id, tipo, nombre, edad) values (555, 'mamifero', 'Avocet, pied', 61);
insert into mascotas (id, tipo, nombre, edad) values (556, 'ave', 'Egret, great', 47);
insert into mascotas (id, tipo, nombre, edad) values (557, 'ave', 'Marabou stork', 80);
insert into mascotas (id, tipo, nombre, edad) values (558, 'mamifero', 'Grison', 53);
insert into mascotas (id, tipo, nombre, edad) values (559, 'mamifero', 'Prairie falcon', 74);
insert into mascotas (id, tipo, nombre, edad) values (560, 'mamifero', 'Kingfisher, white-throated', 68);
insert into mascotas (id, tipo, nombre, edad) values (561, 'ave', 'Red-tailed wambenger', 84);
insert into mascotas (id, tipo, nombre, edad) values (562, 'ave', 'Jungle cat', 9);
insert into mascotas (id, tipo, nombre, edad) values (563, 'mamifero', 'Wombat, common', 69);
insert into mascotas (id, tipo, nombre, edad) values (564, 'mamifero', 'Tortoise, burmese black mountain', 69);
insert into mascotas (id, tipo, nombre, edad) values (565, 'ave', 'Tern, royal', 61);
insert into mascotas (id, tipo, nombre, edad) values (566, 'mamifero', 'Eurasian red squirrel', 88);
insert into mascotas (id, tipo, nombre, edad) values (567, 'mamifero', 'Booby, blue-faced', 107);
insert into mascotas (id, tipo, nombre, edad) values (568, 'ave', 'Land iguana', 8);
insert into mascotas (id, tipo, nombre, edad) values (569, 'mamifero', 'Jaeger, long-tailed', 32);
insert into mascotas (id, tipo, nombre, edad) values (570, 'pez', 'Pie, indian tree', 50);
insert into mascotas (id, tipo, nombre, edad) values (571, 'ave', 'Hornbill, yellow-billed', 106);
insert into mascotas (id, tipo, nombre, edad) values (572, 'mamifero', 'Savanna fox', 68);
insert into mascotas (id, tipo, nombre, edad) values (573, 'pez', 'Common ringtail', 8);
insert into mascotas (id, tipo, nombre, edad) values (574, 'ave', 'Toddy cat', 29);
insert into mascotas (id, tipo, nombre, edad) values (575, 'ave', 'African polecat', 45);
insert into mascotas (id, tipo, nombre, edad) values (576, 'mamifero', 'Tokay gecko', 47);
insert into mascotas (id, tipo, nombre, edad) values (577, 'ave', 'Lion, california sea', 15);
insert into mascotas (id, tipo, nombre, edad) values (578, 'ave', 'Bleeding heart monkey', 28);
insert into mascotas (id, tipo, nombre, edad) values (579, 'ave', 'Siskin, yellow-rumped', 63);
insert into mascotas (id, tipo, nombre, edad) values (580, 'ave', 'Collared lizard', 41);
insert into mascotas (id, tipo, nombre, edad) values (581, 'ave', 'Bohor reedbuck', 43);
insert into mascotas (id, tipo, nombre, edad) values (582, 'mamifero', 'Defassa waterbuck', 25);
insert into mascotas (id, tipo, nombre, edad) values (583, 'ave', 'Huron', 36);
insert into mascotas (id, tipo, nombre, edad) values (584, 'ave', 'Cat, african wild', 106);
insert into mascotas (id, tipo, nombre, edad) values (585, 'mamifero', 'Frogmouth, tawny', 106);
insert into mascotas (id, tipo, nombre, edad) values (586, 'mamifero', 'Dog, bush', 59);
insert into mascotas (id, tipo, nombre, edad) values (587, 'mamifero', 'Black-footed ferret', 75);
insert into mascotas (id, tipo, nombre, edad) values (588, 'ave', 'African skink', 76);
insert into mascotas (id, tipo, nombre, edad) values (589, 'mamifero', 'Booby, blue-faced', 44);
insert into mascotas (id, tipo, nombre, edad) values (590, 'ave', 'Starling, cape', 103);
insert into mascotas (id, tipo, nombre, edad) values (591, 'ave', 'Woylie', 56);
insert into mascotas (id, tipo, nombre, edad) values (592, 'ave', 'Asian openbill', 16);
insert into mascotas (id, tipo, nombre, edad) values (593, 'mamifero', 'Bustard, kori', 34);
insert into mascotas (id, tipo, nombre, edad) values (594, 'mamifero', 'Lemur, lesser mouse', 50);
insert into mascotas (id, tipo, nombre, edad) values (595, 'ave', 'Fox, arctic', 92);
insert into mascotas (id, tipo, nombre, edad) values (596, 'mamifero', 'Bird, secretary', 15);
insert into mascotas (id, tipo, nombre, edad) values (597, 'ave', 'Trotter, lily', 64);
insert into mascotas (id, tipo, nombre, edad) values (598, 'mamifero', 'American woodcock', 17);
insert into mascotas (id, tipo, nombre, edad) values (599, 'mamifero', 'Urial', 34);
insert into mascotas (id, tipo, nombre, edad) values (600, 'mamifero', 'Cat, cape wild', 53);
insert into mascotas (id, tipo, nombre, edad) values (601, 'ave', 'Coqui francolin', 46);
insert into mascotas (id, tipo, nombre, edad) values (602, 'mamifero', 'Vulture, griffon', 43);
insert into mascotas (id, tipo, nombre, edad) values (603, 'ave', 'Emerald-spotted wood dove', 20);
insert into mascotas (id, tipo, nombre, edad) values (604, 'pez', 'Sparrow, rufous-collared', 66);
insert into mascotas (id, tipo, nombre, edad) values (605, 'ave', 'Brindled gnu', 17);
insert into mascotas (id, tipo, nombre, edad) values (606, 'ave', 'Woodcock, american', 80);
insert into mascotas (id, tipo, nombre, edad) values (607, 'mamifero', 'Wagtail, african pied', 15);
insert into mascotas (id, tipo, nombre, edad) values (608, 'mamifero', 'Tortoise, indian star', 91);
insert into mascotas (id, tipo, nombre, edad) values (609, 'ave', 'Black-faced kangaroo', 31);
insert into mascotas (id, tipo, nombre, edad) values (610, 'mamifero', 'Raccoon, common', 17);
insert into mascotas (id, tipo, nombre, edad) values (611, 'ave', 'Koala', 69);
insert into mascotas (id, tipo, nombre, edad) values (612, 'mamifero', 'Cape white-eye', 16);
insert into mascotas (id, tipo, nombre, edad) values (613, 'mamifero', 'Grant''s gazelle', 67);
insert into mascotas (id, tipo, nombre, edad) values (614, 'mamifero', 'African jacana', 105);
insert into mascotas (id, tipo, nombre, edad) values (615, 'mamifero', 'Richardson''s ground squirrel', 71);
insert into mascotas (id, tipo, nombre, edad) values (616, 'mamifero', 'Bird, bare-faced go away', 40);
insert into mascotas (id, tipo, nombre, edad) values (617, 'mamifero', 'Long-finned pilot whale', 46);
insert into mascotas (id, tipo, nombre, edad) values (618, 'mamifero', 'Guanaco', 26);
insert into mascotas (id, tipo, nombre, edad) values (619, 'ave', 'Canadian tiger swallowtail butterfly', 55);
insert into mascotas (id, tipo, nombre, edad) values (620, 'ave', 'Glider, squirrel', 26);
insert into mascotas (id, tipo, nombre, edad) values (621, 'mamifero', 'Grebe, little', 16);
insert into mascotas (id, tipo, nombre, edad) values (622, 'ave', 'Southern lapwing', 19);
insert into mascotas (id, tipo, nombre, edad) values (623, 'mamifero', 'Python, carpet', 11);
insert into mascotas (id, tipo, nombre, edad) values (624, 'ave', 'Alligator, american', 94);
insert into mascotas (id, tipo, nombre, edad) values (625, 'ave', 'Flamingo, lesser', 44);
insert into mascotas (id, tipo, nombre, edad) values (626, 'mamifero', 'Common long-nosed armadillo', 18);
insert into mascotas (id, tipo, nombre, edad) values (627, 'ave', 'Boa, malagasy ground', 53);
insert into mascotas (id, tipo, nombre, edad) values (628, 'mamifero', 'Blue-footed booby', 74);
insert into mascotas (id, tipo, nombre, edad) values (629, 'mamifero', 'Egyptian viper', 52);
insert into mascotas (id, tipo, nombre, edad) values (630, 'ave', 'Civet cat', 50);
insert into mascotas (id, tipo, nombre, edad) values (631, 'mamifero', 'Cow, scottish highland', 87);
insert into mascotas (id, tipo, nombre, edad) values (632, 'mamifero', 'Spider, wolf', 42);
insert into mascotas (id, tipo, nombre, edad) values (633, 'mamifero', 'Monitor lizard (unidentified)', 95);
insert into mascotas (id, tipo, nombre, edad) values (634, 'ave', 'Pie, rufous tree', 98);
insert into mascotas (id, tipo, nombre, edad) values (635, 'mamifero', 'Otter, north american river', 76);
insert into mascotas (id, tipo, nombre, edad) values (636, 'mamifero', 'Javanese cormorant', 61);
insert into mascotas (id, tipo, nombre, edad) values (637, 'pez', 'Hedgehog, south african', 92);
insert into mascotas (id, tipo, nombre, edad) values (638, 'mamifero', 'Screamer, crested', 106);
insert into mascotas (id, tipo, nombre, edad) values (639, 'ave', 'Mallard', 90);
insert into mascotas (id, tipo, nombre, edad) values (640, 'pez', 'Springbok', 69);
insert into mascotas (id, tipo, nombre, edad) values (641, 'ave', 'Fox, north american red', 78);
insert into mascotas (id, tipo, nombre, edad) values (642, 'mamifero', 'Macaw, red and blue', 91);
insert into mascotas (id, tipo, nombre, edad) values (643, 'mamifero', 'Crimson-breasted shrike', 40);
insert into mascotas (id, tipo, nombre, edad) values (644, 'ave', 'Beisa oryx', 26);
insert into mascotas (id, tipo, nombre, edad) values (645, 'mamifero', 'White-eye, cape', 88);
insert into mascotas (id, tipo, nombre, edad) values (646, 'ave', 'Camel, dromedary', 109);
insert into mascotas (id, tipo, nombre, edad) values (647, 'pez', 'Brolga crane', 34);
insert into mascotas (id, tipo, nombre, edad) values (648, 'ave', 'Bennett''s wallaby', 108);
insert into mascotas (id, tipo, nombre, edad) values (649, 'mamifero', 'Eastern grey kangaroo', 96);
insert into mascotas (id, tipo, nombre, edad) values (650, 'pez', 'Vulture, king', 83);
insert into mascotas (id, tipo, nombre, edad) values (651, 'ave', 'Crane, brolga', 39);
insert into mascotas (id, tipo, nombre, edad) values (652, 'mamifero', 'Black-tailed tree creeper', 79);
insert into mascotas (id, tipo, nombre, edad) values (653, 'ave', 'Ox, musk', 9);
insert into mascotas (id, tipo, nombre, edad) values (654, 'pez', 'Snake, western patch-nosed', 25);
insert into mascotas (id, tipo, nombre, edad) values (655, 'pez', 'Vulture, black', 32);
insert into mascotas (id, tipo, nombre, edad) values (656, 'ave', 'African ground squirrel (unidentified)', 103);
insert into mascotas (id, tipo, nombre, edad) values (657, 'ave', 'Wolf, mexican', 41);
insert into mascotas (id, tipo, nombre, edad) values (658, 'ave', 'Dove, white-winged', 31);
insert into mascotas (id, tipo, nombre, edad) values (659, 'mamifero', 'Sloth, pale-throated three-toed', 56);
insert into mascotas (id, tipo, nombre, edad) values (660, 'mamifero', 'Egyptian cobra', 97);
insert into mascotas (id, tipo, nombre, edad) values (661, 'ave', 'Heron, boat-billed', 85);
insert into mascotas (id, tipo, nombre, edad) values (662, 'ave', 'Malabar squirrel', 25);
insert into mascotas (id, tipo, nombre, edad) values (663, 'ave', 'Kangaroo, red', 39);
insert into mascotas (id, tipo, nombre, edad) values (664, 'ave', 'Purple grenadier', 76);
insert into mascotas (id, tipo, nombre, edad) values (665, 'mamifero', 'Impala', 102);
insert into mascotas (id, tipo, nombre, edad) values (666, 'mamifero', 'Jackal, black-backed', 96);
insert into mascotas (id, tipo, nombre, edad) values (667, 'mamifero', 'Lion, steller sea', 64);
insert into mascotas (id, tipo, nombre, edad) values (668, 'mamifero', 'Stork, jabiru', 108);
insert into mascotas (id, tipo, nombre, edad) values (669, 'mamifero', 'Dragon, western bearded', 92);
insert into mascotas (id, tipo, nombre, edad) values (670, 'mamifero', 'Crab, sally lightfoot', 52);
insert into mascotas (id, tipo, nombre, edad) values (671, 'mamifero', 'Olive baboon', 103);
insert into mascotas (id, tipo, nombre, edad) values (672, 'ave', 'Rattlesnake, horned', 108);
insert into mascotas (id, tipo, nombre, edad) values (673, 'ave', 'Monkey, vervet', 38);
insert into mascotas (id, tipo, nombre, edad) values (674, 'ave', 'Plover, three-banded', 43);
insert into mascotas (id, tipo, nombre, edad) values (675, 'mamifero', 'Dog, black-tailed prairie', 32);
insert into mascotas (id, tipo, nombre, edad) values (676, 'ave', 'Common duiker', 35);
insert into mascotas (id, tipo, nombre, edad) values (677, 'mamifero', 'Groundhog', 52);
insert into mascotas (id, tipo, nombre, edad) values (678, 'mamifero', 'Two-toed tree sloth', 28);
insert into mascotas (id, tipo, nombre, edad) values (679, 'mamifero', 'African elephant', 68);
insert into mascotas (id, tipo, nombre, edad) values (680, 'ave', 'Hornbill, red-billed', 49);
insert into mascotas (id, tipo, nombre, edad) values (681, 'ave', 'Kookaburra, laughing', 79);
insert into mascotas (id, tipo, nombre, edad) values (682, 'ave', 'Klipspringer', 104);
insert into mascotas (id, tipo, nombre, edad) values (683, 'ave', 'Goose, egyptian', 81);
insert into mascotas (id, tipo, nombre, edad) values (684, 'ave', 'King cormorant', 44);
insert into mascotas (id, tipo, nombre, edad) values (685, 'ave', 'Pale-throated three-toed sloth', 89);
insert into mascotas (id, tipo, nombre, edad) values (686, 'ave', 'Owl, madagascar hawk', 88);
insert into mascotas (id, tipo, nombre, edad) values (687, 'pez', 'Vulture, bengal', 73);
insert into mascotas (id, tipo, nombre, edad) values (688, 'mamifero', 'Pie, indian tree', 99);
insert into mascotas (id, tipo, nombre, edad) values (689, 'ave', 'Pelican, brown', 31);
insert into mascotas (id, tipo, nombre, edad) values (690, 'ave', 'Oryx, fringe-eared', 57);
insert into mascotas (id, tipo, nombre, edad) values (691, 'mamifero', 'Sloth, hoffman''s', 109);
insert into mascotas (id, tipo, nombre, edad) values (692, 'mamifero', 'Yellow-brown sungazer', 55);
insert into mascotas (id, tipo, nombre, edad) values (693, 'ave', 'Macaque, rhesus', 92);
insert into mascotas (id, tipo, nombre, edad) values (694, 'mamifero', 'Wallaby, river', 8);
insert into mascotas (id, tipo, nombre, edad) values (695, 'ave', 'Giant armadillo', 53);
insert into mascotas (id, tipo, nombre, edad) values (696, 'ave', 'Sheep, american bighorn', 29);
insert into mascotas (id, tipo, nombre, edad) values (697, 'ave', 'Dog, raccoon', 19);
insert into mascotas (id, tipo, nombre, edad) values (698, 'ave', 'Black-eyed bulbul', 22);
insert into mascotas (id, tipo, nombre, edad) values (699, 'mamifero', 'Pelican, australian', 93);
insert into mascotas (id, tipo, nombre, edad) values (700, 'mamifero', 'Lapwing (unidentified)', 79);
insert into mascotas (id, tipo, nombre, edad) values (701, 'ave', 'Great kiskadee', 15);
insert into mascotas (id, tipo, nombre, edad) values (702, 'mamifero', 'Python, carpet', 21);
insert into mascotas (id, tipo, nombre, edad) values (703, 'ave', 'Black-throated cardinal', 13);
insert into mascotas (id, tipo, nombre, edad) values (704, 'ave', 'Bengal vulture', 57);
insert into mascotas (id, tipo, nombre, edad) values (705, 'mamifero', 'Dromedary camel', 45);
insert into mascotas (id, tipo, nombre, edad) values (706, 'mamifero', 'Brush-tailed rat kangaroo', 27);
insert into mascotas (id, tipo, nombre, edad) values (707, 'mamifero', 'Kangaroo, western grey', 73);
insert into mascotas (id, tipo, nombre, edad) values (708, 'mamifero', 'Black-throated butcher bird', 84);
insert into mascotas (id, tipo, nombre, edad) values (709, 'mamifero', 'African elephant', 9);
insert into mascotas (id, tipo, nombre, edad) values (710, 'mamifero', 'Columbian rainbow boa', 71);
insert into mascotas (id, tipo, nombre, edad) values (711, 'mamifero', 'Waxbill, black-cheeked', 28);
insert into mascotas (id, tipo, nombre, edad) values (712, 'mamifero', 'Fowl, helmeted guinea', 56);
insert into mascotas (id, tipo, nombre, edad) values (713, 'pez', 'Western palm tanager (unidentified)', 42);
insert into mascotas (id, tipo, nombre, edad) values (714, 'ave', 'Squirrel, thirteen-lined', 11);
insert into mascotas (id, tipo, nombre, edad) values (715, 'ave', 'Musk ox', 72);
insert into mascotas (id, tipo, nombre, edad) values (716, 'pez', 'Blackish oystercatcher', 54);
insert into mascotas (id, tipo, nombre, edad) values (717, 'mamifero', 'Vine snake (unidentified)', 11);
insert into mascotas (id, tipo, nombre, edad) values (718, 'mamifero', 'Cockatoo, roseate', 25);
insert into mascotas (id, tipo, nombre, edad) values (719, 'mamifero', 'Malay squirrel (unidentified)', 76);
insert into mascotas (id, tipo, nombre, edad) values (720, 'ave', 'Malagasy ground boa', 23);
insert into mascotas (id, tipo, nombre, edad) values (721, 'mamifero', 'Asiatic jackal', 44);
insert into mascotas (id, tipo, nombre, edad) values (722, 'ave', 'Southern black-backed gull', 67);
insert into mascotas (id, tipo, nombre, edad) values (723, 'pez', 'Hornbill, southern ground', 72);
insert into mascotas (id, tipo, nombre, edad) values (724, 'mamifero', 'Sloth bear', 30);
insert into mascotas (id, tipo, nombre, edad) values (725, 'mamifero', 'Australian sea lion', 46);
insert into mascotas (id, tipo, nombre, edad) values (726, 'mamifero', 'Woodpecker, red-headed', 61);
insert into mascotas (id, tipo, nombre, edad) values (727, 'mamifero', 'Yellow-bellied marmot', 62);
insert into mascotas (id, tipo, nombre, edad) values (728, 'ave', 'European badger', 102);
insert into mascotas (id, tipo, nombre, edad) values (729, 'mamifero', 'Giant armadillo', 99);
insert into mascotas (id, tipo, nombre, edad) values (730, 'mamifero', 'Civet cat', 32);
insert into mascotas (id, tipo, nombre, edad) values (731, 'ave', 'Snowy egret', 101);
insert into mascotas (id, tipo, nombre, edad) values (732, 'pez', 'Chacma baboon', 56);
insert into mascotas (id, tipo, nombre, edad) values (733, 'ave', 'White-faced tree rat', 58);
insert into mascotas (id, tipo, nombre, edad) values (734, 'ave', 'White-nosed coatimundi', 32);
insert into mascotas (id, tipo, nombre, edad) values (735, 'ave', 'Frilled dragon', 103);
insert into mascotas (id, tipo, nombre, edad) values (736, 'mamifero', 'Fox, blue', 61);
insert into mascotas (id, tipo, nombre, edad) values (737, 'mamifero', 'Pig-tailed macaque', 64);
insert into mascotas (id, tipo, nombre, edad) values (738, 'ave', 'Lizard, giant girdled', 18);
insert into mascotas (id, tipo, nombre, edad) values (739, 'ave', 'Striped dolphin', 57);
insert into mascotas (id, tipo, nombre, edad) values (740, 'mamifero', 'Paca', 54);
insert into mascotas (id, tipo, nombre, edad) values (741, 'ave', 'Snake, eastern indigo', 58);
insert into mascotas (id, tipo, nombre, edad) values (742, 'mamifero', 'Penguin, little blue', 49);
insert into mascotas (id, tipo, nombre, edad) values (743, 'ave', 'Cape white-eye', 109);
insert into mascotas (id, tipo, nombre, edad) values (744, 'ave', 'Cat, tiger', 71);
insert into mascotas (id, tipo, nombre, edad) values (745, 'ave', 'Rufous tree pie', 72);
insert into mascotas (id, tipo, nombre, edad) values (746, 'ave', 'Yellow-throated sandgrouse', 56);
insert into mascotas (id, tipo, nombre, edad) values (747, 'ave', 'Common dolphin', 105);
insert into mascotas (id, tipo, nombre, edad) values (748, 'ave', 'Capuchin, white-fronted', 30);
insert into mascotas (id, tipo, nombre, edad) values (749, 'mamifero', 'Long-billed cockatoo', 44);
insert into mascotas (id, tipo, nombre, edad) values (750, 'ave', 'Desert tortoise', 62);
insert into mascotas (id, tipo, nombre, edad) values (751, 'mamifero', 'Starling, greater blue-eared', 47);
insert into mascotas (id, tipo, nombre, edad) values (752, 'mamifero', 'Sloth, pale-throated three-toed', 57);
insert into mascotas (id, tipo, nombre, edad) values (753, 'pez', 'Vulture, turkey', 22);
insert into mascotas (id, tipo, nombre, edad) values (754, 'ave', 'Squirrel, palm', 89);
insert into mascotas (id, tipo, nombre, edad) values (755, 'mamifero', 'Catfish, blue', 66);
insert into mascotas (id, tipo, nombre, edad) values (756, 'mamifero', 'Red kangaroo', 51);
insert into mascotas (id, tipo, nombre, edad) values (757, 'ave', 'Pine siskin', 23);
insert into mascotas (id, tipo, nombre, edad) values (758, 'ave', 'Stork, yellow-billed', 60);
insert into mascotas (id, tipo, nombre, edad) values (759, 'ave', 'Black-fronted bulbul', 59);
insert into mascotas (id, tipo, nombre, edad) values (760, 'mamifero', 'Rhea, common', 47);
insert into mascotas (id, tipo, nombre, edad) values (761, 'mamifero', 'Squirrel, antelope ground', 93);
insert into mascotas (id, tipo, nombre, edad) values (762, 'ave', 'Cat, tiger', 25);
insert into mascotas (id, tipo, nombre, edad) values (763, 'pez', 'Corella, long-billed', 108);
insert into mascotas (id, tipo, nombre, edad) values (764, 'mamifero', 'Dama wallaby', 108);
insert into mascotas (id, tipo, nombre, edad) values (765, 'ave', 'Gazelle, thomson''s', 105);
insert into mascotas (id, tipo, nombre, edad) values (766, 'ave', 'Golden brush-tailed possum', 9);
insert into mascotas (id, tipo, nombre, edad) values (767, 'mamifero', 'Jungle kangaroo', 23);
insert into mascotas (id, tipo, nombre, edad) values (768, 'mamifero', 'Squirrel, antelope ground', 104);
insert into mascotas (id, tipo, nombre, edad) values (769, 'ave', 'Sloth, two-toed tree', 100);
insert into mascotas (id, tipo, nombre, edad) values (770, 'ave', 'Ant (unidentified)', 50);
insert into mascotas (id, tipo, nombre, edad) values (771, 'ave', 'Asiatic jackal', 42);
insert into mascotas (id, tipo, nombre, edad) values (772, 'pez', 'Mississippi alligator', 27);
insert into mascotas (id, tipo, nombre, edad) values (773, 'pez', 'Olive baboon', 42);
insert into mascotas (id, tipo, nombre, edad) values (774, 'mamifero', 'Jackrabbit, white-tailed', 53);
insert into mascotas (id, tipo, nombre, edad) values (775, 'ave', 'Jackal, asiatic', 15);
insert into mascotas (id, tipo, nombre, edad) values (776, 'mamifero', 'Asian water buffalo', 20);
insert into mascotas (id, tipo, nombre, edad) values (777, 'mamifero', 'Buffalo, asian water', 84);
insert into mascotas (id, tipo, nombre, edad) values (778, 'ave', 'Bateleur eagle', 50);
insert into mascotas (id, tipo, nombre, edad) values (779, 'ave', 'Duiker, gray', 88);
insert into mascotas (id, tipo, nombre, edad) values (780, 'pez', 'Pied kingfisher', 32);
insert into mascotas (id, tipo, nombre, edad) values (781, 'mamifero', 'White-mantled colobus', 89);
insert into mascotas (id, tipo, nombre, edad) values (782, 'pez', 'Leopard', 62);
insert into mascotas (id, tipo, nombre, edad) values (783, 'mamifero', 'Vulture, turkey', 97);
insert into mascotas (id, tipo, nombre, edad) values (784, 'ave', 'Sloth, two-toed tree', 17);
insert into mascotas (id, tipo, nombre, edad) values (785, 'ave', 'Southern boubou', 81);
insert into mascotas (id, tipo, nombre, edad) values (786, 'ave', 'Comb duck', 31);
insert into mascotas (id, tipo, nombre, edad) values (787, 'mamifero', 'Snake, carpet', 72);
insert into mascotas (id, tipo, nombre, edad) values (788, 'mamifero', 'Rufous-collared sparrow', 101);
insert into mascotas (id, tipo, nombre, edad) values (789, 'mamifero', 'Dik, kirk''s dik', 43);
insert into mascotas (id, tipo, nombre, edad) values (790, 'pez', 'White-tailed deer', 62);
insert into mascotas (id, tipo, nombre, edad) values (791, 'mamifero', 'Tsessebe', 78);
insert into mascotas (id, tipo, nombre, edad) values (792, 'mamifero', 'Crane, brolga', 94);
insert into mascotas (id, tipo, nombre, edad) values (793, 'mamifero', 'Red-tailed wambenger', 34);
insert into mascotas (id, tipo, nombre, edad) values (794, 'pez', 'Collared lemming', 62);
insert into mascotas (id, tipo, nombre, edad) values (795, 'pez', 'Purple grenadier', 64);
insert into mascotas (id, tipo, nombre, edad) values (796, 'ave', 'European stork', 30);
insert into mascotas (id, tipo, nombre, edad) values (797, 'ave', 'Bare-faced go away bird', 33);
insert into mascotas (id, tipo, nombre, edad) values (798, 'ave', 'Bird, bare-faced go away', 89);
insert into mascotas (id, tipo, nombre, edad) values (799, 'mamifero', 'Wallaby, agile', 102);
insert into mascotas (id, tipo, nombre, edad) values (800, 'ave', 'Desert tortoise', 8);
insert into mascotas (id, tipo, nombre, edad) values (801, 'ave', 'Swallow (unidentified)', 94);
insert into mascotas (id, tipo, nombre, edad) values (802, 'mamifero', 'Collared lemming', 65);
insert into mascotas (id, tipo, nombre, edad) values (803, 'mamifero', 'Waxbill, blue', 36);
insert into mascotas (id, tipo, nombre, edad) values (804, 'mamifero', 'Sockeye salmon', 107);
insert into mascotas (id, tipo, nombre, edad) values (805, 'ave', 'Cape fox', 14);
insert into mascotas (id, tipo, nombre, edad) values (806, 'ave', 'Fox, north american red', 53);
insert into mascotas (id, tipo, nombre, edad) values (807, 'mamifero', 'Emerald green tree boa', 41);
insert into mascotas (id, tipo, nombre, edad) values (808, 'mamifero', 'Southern elephant seal', 87);
insert into mascotas (id, tipo, nombre, edad) values (809, 'ave', 'Gulls (unidentified)', 92);
insert into mascotas (id, tipo, nombre, edad) values (810, 'mamifero', 'Siskin, yellow-rumped', 96);
insert into mascotas (id, tipo, nombre, edad) values (811, 'mamifero', 'Agouti', 77);
insert into mascotas (id, tipo, nombre, edad) values (812, 'mamifero', 'Jackal, indian', 32);
insert into mascotas (id, tipo, nombre, edad) values (813, 'ave', 'Common ringtail', 33);
insert into mascotas (id, tipo, nombre, edad) values (814, 'ave', 'Black-cheeked waxbill', 22);
insert into mascotas (id, tipo, nombre, edad) values (815, 'ave', 'Raccoon dog', 35);
insert into mascotas (id, tipo, nombre, edad) values (816, 'pez', 'Ibis, glossy', 107);
insert into mascotas (id, tipo, nombre, edad) values (817, 'mamifero', 'Insect, stick', 85);
insert into mascotas (id, tipo, nombre, edad) values (818, 'ave', 'Capuchin, black-capped', 105);
insert into mascotas (id, tipo, nombre, edad) values (819, 'mamifero', 'Old world fruit bat (unidentified)', 70);
insert into mascotas (id, tipo, nombre, edad) values (820, 'ave', 'Eland, common', 38);
insert into mascotas (id, tipo, nombre, edad) values (821, 'ave', 'Savanna fox', 95);
insert into mascotas (id, tipo, nombre, edad) values (822, 'ave', 'Tiger snake', 95);
insert into mascotas (id, tipo, nombre, edad) values (823, 'mamifero', 'Kangaroo, black-faced', 8);
insert into mascotas (id, tipo, nombre, edad) values (824, 'ave', 'Spotted wood sandpiper', 15);
insert into mascotas (id, tipo, nombre, edad) values (825, 'mamifero', 'Pheasant, ring-necked', 38);
insert into mascotas (id, tipo, nombre, edad) values (826, 'mamifero', 'Wild turkey', 105);
insert into mascotas (id, tipo, nombre, edad) values (827, 'ave', 'Trumpeter swan', 104);
insert into mascotas (id, tipo, nombre, edad) values (828, 'pez', 'Lizard, frilled', 31);
insert into mascotas (id, tipo, nombre, edad) values (829, 'ave', 'Dark-winged trumpeter', 44);
insert into mascotas (id, tipo, nombre, edad) values (830, 'ave', 'Pied crow', 89);
insert into mascotas (id, tipo, nombre, edad) values (831, 'ave', 'Phalarope, grey', 102);
insert into mascotas (id, tipo, nombre, edad) values (832, 'mamifero', 'American woodcock', 65);
insert into mascotas (id, tipo, nombre, edad) values (833, 'mamifero', 'Deer, savannah', 108);
insert into mascotas (id, tipo, nombre, edad) values (834, 'pez', 'Macaw, blue and gold', 55);
insert into mascotas (id, tipo, nombre, edad) values (835, 'ave', 'Leopard', 87);
insert into mascotas (id, tipo, nombre, edad) values (836, 'pez', 'Gulls (unidentified)', 27);
insert into mascotas (id, tipo, nombre, edad) values (837, 'ave', 'Catfish, blue', 56);
insert into mascotas (id, tipo, nombre, edad) values (838, 'mamifero', 'Flamingo, roseat', 78);
insert into mascotas (id, tipo, nombre, edad) values (839, 'ave', 'Mountain duck', 87);
insert into mascotas (id, tipo, nombre, edad) values (840, 'mamifero', 'Snake, buttermilk', 93);
insert into mascotas (id, tipo, nombre, edad) values (841, 'mamifero', 'Sloth, pale-throated three-toed', 65);
insert into mascotas (id, tipo, nombre, edad) values (842, 'mamifero', 'Lemur, grey mouse', 58);
insert into mascotas (id, tipo, nombre, edad) values (843, 'ave', 'Golden-mantled ground squirrel', 31);
insert into mascotas (id, tipo, nombre, edad) values (844, 'mamifero', 'Kangaroo, eastern grey', 51);
insert into mascotas (id, tipo, nombre, edad) values (845, 'mamifero', 'Pied butcher bird', 55);
insert into mascotas (id, tipo, nombre, edad) values (846, 'ave', 'Avocet, pied', 72);
insert into mascotas (id, tipo, nombre, edad) values (847, 'mamifero', 'Lemming, collared', 72);
insert into mascotas (id, tipo, nombre, edad) values (848, 'ave', 'Woodpecker, red-headed', 21);
insert into mascotas (id, tipo, nombre, edad) values (849, 'ave', 'African wild dog', 17);
insert into mascotas (id, tipo, nombre, edad) values (850, 'ave', 'Possum, golden brush-tailed', 26);
insert into mascotas (id, tipo, nombre, edad) values (851, 'mamifero', 'Fox, silver-backed', 19);
insert into mascotas (id, tipo, nombre, edad) values (852, 'ave', 'Zorro, common', 81);
insert into mascotas (id, tipo, nombre, edad) values (853, 'mamifero', 'Coqui partridge', 48);
insert into mascotas (id, tipo, nombre, edad) values (854, 'ave', 'Sparrow, rufous-collared', 58);
insert into mascotas (id, tipo, nombre, edad) values (855, 'ave', 'Impala', 83);
insert into mascotas (id, tipo, nombre, edad) values (856, 'mamifero', 'Leopard', 10);
insert into mascotas (id, tipo, nombre, edad) values (857, 'mamifero', 'Savannah deer', 85);
insert into mascotas (id, tipo, nombre, edad) values (858, 'ave', 'Gray langur', 10);
insert into mascotas (id, tipo, nombre, edad) values (859, 'mamifero', 'Canada goose', 33);
insert into mascotas (id, tipo, nombre, edad) values (860, 'ave', 'Mara', 108);
insert into mascotas (id, tipo, nombre, edad) values (861, 'ave', 'Gull, pacific', 101);
insert into mascotas (id, tipo, nombre, edad) values (862, 'ave', 'Wolf, mexican', 102);
insert into mascotas (id, tipo, nombre, edad) values (863, 'mamifero', 'Wambenger, red-tailed', 87);
insert into mascotas (id, tipo, nombre, edad) values (864, 'ave', 'Turtle, snake-necked', 65);
insert into mascotas (id, tipo, nombre, edad) values (865, 'ave', 'Common ringtail', 29);
insert into mascotas (id, tipo, nombre, edad) values (866, 'mamifero', 'Long-crested hawk eagle', 88);
insert into mascotas (id, tipo, nombre, edad) values (867, 'mamifero', 'Common grenadier', 57);
insert into mascotas (id, tipo, nombre, edad) values (868, 'pez', 'Coot, red-knobbed', 26);
insert into mascotas (id, tipo, nombre, edad) values (869, 'mamifero', 'Greater rhea', 101);
insert into mascotas (id, tipo, nombre, edad) values (870, 'pez', 'Southern right whale', 58);
insert into mascotas (id, tipo, nombre, edad) values (871, 'mamifero', 'Stanley bustard', 28);
insert into mascotas (id, tipo, nombre, edad) values (872, 'pez', 'Woodcock, american', 31);
insert into mascotas (id, tipo, nombre, edad) values (873, 'mamifero', 'Hoary marmot', 96);
insert into mascotas (id, tipo, nombre, edad) values (874, 'ave', 'Ibis, glossy', 41);
insert into mascotas (id, tipo, nombre, edad) values (875, 'ave', 'Macaw, blue and yellow', 84);
insert into mascotas (id, tipo, nombre, edad) values (876, 'mamifero', 'Possum, ring-tailed', 54);
insert into mascotas (id, tipo, nombre, edad) values (877, 'pez', 'Brown and yellow marshbird', 79);
insert into mascotas (id, tipo, nombre, edad) values (878, 'mamifero', 'Steller''s sea lion', 86);
insert into mascotas (id, tipo, nombre, edad) values (879, 'mamifero', 'Flying fox (unidentified)', 38);
insert into mascotas (id, tipo, nombre, edad) values (880, 'ave', 'White-winged tern', 94);
insert into mascotas (id, tipo, nombre, edad) values (881, 'mamifero', 'Savanna fox', 77);
insert into mascotas (id, tipo, nombre, edad) values (882, 'pez', 'Peccary, white-lipped', 18);
insert into mascotas (id, tipo, nombre, edad) values (883, 'ave', 'Lion, california sea', 95);
insert into mascotas (id, tipo, nombre, edad) values (884, 'mamifero', 'Greater roadrunner', 8);
insert into mascotas (id, tipo, nombre, edad) values (885, 'ave', 'Lion, steller sea', 15);
insert into mascotas (id, tipo, nombre, edad) values (886, 'mamifero', 'Mongoose, javan gold-spotted', 85);
insert into mascotas (id, tipo, nombre, edad) values (887, 'ave', 'Australian magpie', 35);
insert into mascotas (id, tipo, nombre, edad) values (888, 'ave', 'Buttermilk snake', 82);
insert into mascotas (id, tipo, nombre, edad) values (889, 'mamifero', 'Tawny frogmouth', 12);
insert into mascotas (id, tipo, nombre, edad) values (890, 'mamifero', 'Tortoise, radiated', 49);
insert into mascotas (id, tipo, nombre, edad) values (891, 'mamifero', 'Hyena, striped', 101);
insert into mascotas (id, tipo, nombre, edad) values (892, 'mamifero', 'Black-crowned crane', 94);
insert into mascotas (id, tipo, nombre, edad) values (893, 'pez', 'Coke''s hartebeest', 101);
insert into mascotas (id, tipo, nombre, edad) values (894, 'ave', 'Ring-necked pheasant', 67);
insert into mascotas (id, tipo, nombre, edad) values (895, 'mamifero', 'Sun gazer', 8);
insert into mascotas (id, tipo, nombre, edad) values (896, 'mamifero', 'Wapiti, elk,', 95);
insert into mascotas (id, tipo, nombre, edad) values (897, 'mamifero', 'Orca', 93);
insert into mascotas (id, tipo, nombre, edad) values (898, 'mamifero', 'Plains zebra', 39);
insert into mascotas (id, tipo, nombre, edad) values (899, 'ave', 'Wattled crane', 21);
insert into mascotas (id, tipo, nombre, edad) values (900, 'mamifero', 'Marshbird, brown and yellow', 36);
insert into mascotas (id, tipo, nombre, edad) values (901, 'mamifero', 'Tern, royal', 33);
insert into mascotas (id, tipo, nombre, edad) values (902, 'ave', 'Yellow-crowned night heron', 104);
insert into mascotas (id, tipo, nombre, edad) values (903, 'ave', 'Mouflon', 101);
insert into mascotas (id, tipo, nombre, edad) values (904, 'ave', 'Bottle-nose dolphin', 22);
insert into mascotas (id, tipo, nombre, edad) values (905, 'ave', 'Miner''s cat', 62);
insert into mascotas (id, tipo, nombre, edad) values (906, 'ave', 'Crane, sandhill', 37);
insert into mascotas (id, tipo, nombre, edad) values (907, 'ave', 'Sociable weaver', 39);
insert into mascotas (id, tipo, nombre, edad) values (908, 'mamifero', 'Rufous tree pie', 60);
insert into mascotas (id, tipo, nombre, edad) values (909, 'mamifero', 'Skua, great', 62);
insert into mascotas (id, tipo, nombre, edad) values (910, 'ave', 'Striped dolphin', 16);
insert into mascotas (id, tipo, nombre, edad) values (911, 'ave', 'Ornate rock dragon', 91);
insert into mascotas (id, tipo, nombre, edad) values (912, 'ave', 'Fox, grey', 90);
insert into mascotas (id, tipo, nombre, edad) values (913, 'ave', 'Lourie, grey', 19);
insert into mascotas (id, tipo, nombre, edad) values (914, 'mamifero', 'Collared lemming', 22);
insert into mascotas (id, tipo, nombre, edad) values (915, 'ave', 'African polecat', 103);
insert into mascotas (id, tipo, nombre, edad) values (916, 'pez', 'Steller''s sea lion', 50);
insert into mascotas (id, tipo, nombre, edad) values (917, 'ave', 'Ibis, sacred', 29);
insert into mascotas (id, tipo, nombre, edad) values (918, 'ave', 'Galah', 83);
insert into mascotas (id, tipo, nombre, edad) values (919, 'pez', 'Leopard', 87);
insert into mascotas (id, tipo, nombre, edad) values (920, 'mamifero', 'Jackal, indian', 41);
insert into mascotas (id, tipo, nombre, edad) values (921, 'mamifero', 'Dusky gull', 82);
insert into mascotas (id, tipo, nombre, edad) values (922, 'ave', 'Chameleon (unidentified)', 23);
insert into mascotas (id, tipo, nombre, edad) values (923, 'ave', 'Kudu, greater', 37);
insert into mascotas (id, tipo, nombre, edad) values (924, 'ave', 'Sungazer, yellow-brown', 37);
insert into mascotas (id, tipo, nombre, edad) values (925, 'mamifero', 'Fairy penguin', 73);
insert into mascotas (id, tipo, nombre, edad) values (926, 'mamifero', 'Macaw, blue and yellow', 82);
insert into mascotas (id, tipo, nombre, edad) values (927, 'mamifero', 'Butterfly, canadian tiger swallowtail', 82);
insert into mascotas (id, tipo, nombre, edad) values (928, 'pez', 'Large-eared bushbaby', 54);
insert into mascotas (id, tipo, nombre, edad) values (929, 'mamifero', 'Phalarope, grey', 77);
insert into mascotas (id, tipo, nombre, edad) values (930, 'ave', 'Laughing kookaburra', 29);
insert into mascotas (id, tipo, nombre, edad) values (931, 'ave', 'Penguin, magellanic', 95);
insert into mascotas (id, tipo, nombre, edad) values (932, 'mamifero', 'Kangaroo, brush-tailed rat', 61);
insert into mascotas (id, tipo, nombre, edad) values (933, 'ave', 'Agile wallaby', 102);
insert into mascotas (id, tipo, nombre, edad) values (934, 'mamifero', 'Lesser masked weaver', 84);
insert into mascotas (id, tipo, nombre, edad) values (935, 'pez', 'Ferruginous hawk', 32);
insert into mascotas (id, tipo, nombre, edad) values (936, 'pez', 'Bulbul, african red-eyed', 80);
insert into mascotas (id, tipo, nombre, edad) values (937, 'mamifero', 'Greater roadrunner', 38);
insert into mascotas (id, tipo, nombre, edad) values (938, 'mamifero', 'Frilled dragon', 20);
insert into mascotas (id, tipo, nombre, edad) values (939, 'ave', 'Cat, native', 96);
insert into mascotas (id, tipo, nombre, edad) values (940, 'ave', 'Black-cheeked waxbill', 57);
insert into mascotas (id, tipo, nombre, edad) values (941, 'mamifero', 'Lynx, african', 17);
insert into mascotas (id, tipo, nombre, edad) values (942, 'mamifero', 'Red-billed toucan', 88);
insert into mascotas (id, tipo, nombre, edad) values (943, 'mamifero', 'Lion, australian sea', 94);
insert into mascotas (id, tipo, nombre, edad) values (944, 'mamifero', 'Rhea, gray', 60);
insert into mascotas (id, tipo, nombre, edad) values (945, 'ave', 'Indian peacock', 85);
insert into mascotas (id, tipo, nombre, edad) values (946, 'mamifero', 'Fat-tailed dunnart', 20);
insert into mascotas (id, tipo, nombre, edad) values (947, 'ave', 'Red-tailed wambenger', 83);
insert into mascotas (id, tipo, nombre, edad) values (948, 'ave', 'Plover, blacksmith', 46);
insert into mascotas (id, tipo, nombre, edad) values (949, 'mamifero', 'Red-billed tropic bird', 41);
insert into mascotas (id, tipo, nombre, edad) values (950, 'ave', 'Arboral spiny rat', 75);
insert into mascotas (id, tipo, nombre, edad) values (951, 'pez', 'Kafue flats lechwe', 96);
insert into mascotas (id, tipo, nombre, edad) values (952, 'mamifero', 'Arctic tern', 80);
insert into mascotas (id, tipo, nombre, edad) values (953, 'mamifero', 'Indian giant squirrel', 15);
insert into mascotas (id, tipo, nombre, edad) values (954, 'ave', 'Squirrel, red', 29);
insert into mascotas (id, tipo, nombre, edad) values (955, 'ave', 'European beaver', 82);
insert into mascotas (id, tipo, nombre, edad) values (956, 'ave', 'Curlew, black', 49);
insert into mascotas (id, tipo, nombre, edad) values (957, 'mamifero', 'Cormorant, neotropic', 43);
insert into mascotas (id, tipo, nombre, edad) values (958, 'ave', 'Glider, sugar', 66);
insert into mascotas (id, tipo, nombre, edad) values (959, 'ave', 'Heron, gray', 59);
insert into mascotas (id, tipo, nombre, edad) values (960, 'ave', 'Stone sheep', 61);
insert into mascotas (id, tipo, nombre, edad) values (961, 'mamifero', 'Swan, trumpeter', 61);
insert into mascotas (id, tipo, nombre, edad) values (962, 'ave', 'Goose, egyptian', 45);
insert into mascotas (id, tipo, nombre, edad) values (963, 'mamifero', 'Butterfly (unidentified)', 94);
insert into mascotas (id, tipo, nombre, edad) values (964, 'mamifero', 'Pintail, white-cheeked', 94);
insert into mascotas (id, tipo, nombre, edad) values (965, 'ave', 'Vulture, white-rumped', 97);
insert into mascotas (id, tipo, nombre, edad) values (966, 'pez', 'Cook''s tree boa', 53);
insert into mascotas (id, tipo, nombre, edad) values (967, 'ave', 'Bear, polar', 51);
insert into mascotas (id, tipo, nombre, edad) values (968, 'mamifero', 'Whale, long-finned pilot', 52);
insert into mascotas (id, tipo, nombre, edad) values (969, 'mamifero', 'Porcupine, north american', 43);
insert into mascotas (id, tipo, nombre, edad) values (970, 'ave', 'Chestnut weaver', 53);
insert into mascotas (id, tipo, nombre, edad) values (971, 'ave', 'Vulture, griffon', 54);
insert into mascotas (id, tipo, nombre, edad) values (972, 'ave', 'White-winged tern', 92);
insert into mascotas (id, tipo, nombre, edad) values (973, 'ave', 'Galah', 26);
insert into mascotas (id, tipo, nombre, edad) values (974, 'mamifero', 'Campo flicker', 20);
insert into mascotas (id, tipo, nombre, edad) values (975, 'ave', 'African fish eagle', 82);
insert into mascotas (id, tipo, nombre, edad) values (976, 'pez', 'Bandicoot, short-nosed', 63);
insert into mascotas (id, tipo, nombre, edad) values (977, 'pez', 'Red-breasted nuthatch', 51);
insert into mascotas (id, tipo, nombre, edad) values (978, 'mamifero', 'Japanese macaque', 39);
insert into mascotas (id, tipo, nombre, edad) values (979, 'mamifero', 'Dragon, western bearded', 10);
insert into mascotas (id, tipo, nombre, edad) values (980, 'ave', 'Cape cobra', 92);
insert into mascotas (id, tipo, nombre, edad) values (981, 'ave', 'Magpie, black-backed', 67);
insert into mascotas (id, tipo, nombre, edad) values (982, 'ave', 'Chestnut weaver', 18);
insert into mascotas (id, tipo, nombre, edad) values (983, 'pez', 'Cape fox', 101);
insert into mascotas (id, tipo, nombre, edad) values (984, 'mamifero', 'Galapagos mockingbird', 94);
insert into mascotas (id, tipo, nombre, edad) values (985, 'ave', 'Rhesus macaque', 109);
insert into mascotas (id, tipo, nombre, edad) values (986, 'mamifero', 'Russian dragonfly', 109);
insert into mascotas (id, tipo, nombre, edad) values (987, 'mamifero', 'Pelican, eastern white', 36);
insert into mascotas (id, tipo, nombre, edad) values (988, 'pez', 'Hare, arctic', 40);
insert into mascotas (id, tipo, nombre, edad) values (989, 'ave', 'Macaw, red and blue', 95);
insert into mascotas (id, tipo, nombre, edad) values (990, 'ave', 'Owl, burrowing', 43);
insert into mascotas (id, tipo, nombre, edad) values (991, 'mamifero', 'Waxbill, blue', 54);
insert into mascotas (id, tipo, nombre, edad) values (992, 'ave', 'Plover, three-banded', 30);
insert into mascotas (id, tipo, nombre, edad) values (993, 'mamifero', 'Green-winged macaw', 53);
insert into mascotas (id, tipo, nombre, edad) values (994, 'ave', 'Wood pigeon', 80);
insert into mascotas (id, tipo, nombre, edad) values (995, 'pez', 'Springbuck', 93);
insert into mascotas (id, tipo, nombre, edad) values (996, 'mamifero', 'Asian water dragon', 47);
insert into mascotas (id, tipo, nombre, edad) values (997, 'mamifero', 'Pale-throated three-toed sloth', 94);
insert into mascotas (id, tipo, nombre, edad) values (998, 'mamifero', 'Kaffir cat', 48);
insert into mascotas (id, tipo, nombre, edad) values (999, 'ave', 'Common wombat', 9);
insert into mascotas (id, tipo, nombre, edad) values (1000, 'mamifero', 'Burmese black mountain tortoise', 84);
